"""Report generator -- takes module summaries + LLM client, generates each report file.

Each report is generated by:
1. Formatting the prompt template with context data
2. Calling the LLM
3. Saving the markdown output to data/outputs/{task_id}/XX-报告名.md
"""

import logging
from datetime import datetime, timezone
from pathlib import Path

from app.llm.base import BaseLLMClient, LLMResponse
from app.prompts.schemas import REPORT_FILE_MAP
from app.prompts.templates import (
    BUSINESS_FLOW_PROMPT,
    MODULE_MAP_PROMPT,
    REQUIREMENTS_PROMPT,
    SOURCE_READING_PROMPT,
    TEST_DESIGN_PROMPT,
    TRACEABILITY_PROMPT,
)

logger = logging.getLogger(__name__)

MAX_OUTPUT_TOKENS = 4096


class ReportGenerator:
    """Generates analysis report files from module summaries via LLM."""

    def __init__(
        self,
        llm_client: BaseLLMClient,
        output_dir: Path,
        task_id: str,
    ) -> None:
        self._llm = llm_client
        self._output_dir = output_dir
        self._task_id = task_id
        self._generated_files: list[str] = []

    @property
    def generated_files(self) -> list[str]:
        return list(self._generated_files)

    async def generate_all(
        self,
        module_summaries: list[dict],
        gitnexus_data: dict,
        deepwiki_data: dict,
        requirements_doc: str | None = None,
        design_doc: str | None = None,
        analysis_focus: str = "",
        prompt_content: str = "",
    ) -> list[str]:
        """Generate all applicable reports and return list of filenames."""
        summaries_text = self._format_summaries(module_summaries)

        content_prefix = ""
        if prompt_content:
            content_prefix = (
                f"## 用户自定义分析提示词\n{prompt_content[:4000]}\n\n"
                "请参考以上分析方法论和要求展开分析。\n\n"
            )
        elif analysis_focus:
            content_prefix = (
                f"## 用户分析目标\n{analysis_focus}\n\n"
                "请围绕此目标重点展开分析。\n\n"
            )

        # Always generate the four core reports
        await self._generate_report(
            report_type="module_map",
            prompt=content_prefix + MODULE_MAP_PROMPT.format(
                project_overview=self._build_project_overview(gitnexus_data, deepwiki_data),
                module_summaries=summaries_text,
                inter_module_deps=self._build_inter_module_deps(gitnexus_data),
            ),
        )

        await self._generate_report(
            report_type="business_flow",
            prompt=content_prefix + BUSINESS_FLOW_PROMPT.format(
                module_summaries=summaries_text,
                process_data=self._build_process_data(gitnexus_data),
                cross_module_calls=self._build_cross_module_calls(gitnexus_data),
            ),
        )

        await self._generate_report(
            report_type="source_reading",
            prompt=content_prefix + SOURCE_READING_PROMPT.format(
                module_summaries=summaries_text,
                key_files=self._build_key_files(gitnexus_data),
                call_graph=self._build_call_graph(gitnexus_data),
            ),
        )

        await self._generate_report(
            report_type="test_design",
            prompt=content_prefix + TEST_DESIGN_PROMPT.format(
                module_summaries=summaries_text,
                business_flows=self._build_process_data(gitnexus_data),
                api_interfaces=self._build_api_interfaces(gitnexus_data),
            ),
        )

        # Optional reports: only if requirements/design docs provided
        if requirements_doc:
            await self._generate_report(
                report_type="requirements",
                prompt=content_prefix + REQUIREMENTS_PROMPT.format(
                    requirements_doc=self._truncate(requirements_doc, 5000),
                    design_doc=self._truncate(design_doc or "（未提供设计文档）", 5000),
                    module_summaries=summaries_text,
                ),
            )

        if requirements_doc and design_doc:
            await self._generate_report(
                report_type="traceability",
                prompt=content_prefix + TRACEABILITY_PROMPT.format(
                    requirements_items=self._truncate(requirements_doc, 3000),
                    design_modules=self._truncate(design_doc, 3000),
                    module_summaries=summaries_text,
                    call_relations=self._build_call_graph(gitnexus_data),
                ),
            )

        return self._generated_files

    async def _generate_report(self, report_type: str, prompt: str) -> None:
        """Generate a single report and save to disk."""
        filename = REPORT_FILE_MAP.get(report_type)
        if not filename:
            logger.warning("Unknown report type: %s", report_type)
            return

        try:
            messages = [{"role": "user", "content": prompt}]
            response: LLMResponse = await self._llm.complete(
                messages=messages,
                max_tokens=MAX_OUTPUT_TOKENS,
                temperature=0.3,
            )

            # Prepend metadata header
            now = datetime.now(timezone.utc).isoformat()
            header = (
                f"---\n"
                f"report_type: {report_type}\n"
                f"task_id: {self._task_id}\n"
                f"generated_at: {now}\n"
                f"model: {response.model}\n"
                f"tokens: {response.usage.get('total_tokens', 0)}\n"
                f"---\n\n"
            )

            filepath = self._output_dir / filename
            filepath.write_text(header + response.content, encoding="utf-8")
            self._generated_files.append(filename)

            logger.info(
                "Report %s generated: %s (%d tokens)",
                report_type,
                filename,
                response.usage.get("total_tokens", 0),
            )

        except Exception as exc:
            logger.error("Report generation failed for %s: %s", report_type, exc)

    # ------------------------------------------------------------------
    # Context builders -- extract relevant data for each prompt
    # ------------------------------------------------------------------

    @staticmethod
    def _format_summaries(module_summaries: list[dict]) -> str:
        """Format module summaries for inclusion in report prompts."""
        parts: list[str] = []
        for ms in module_summaries:
            parts.append(f"### {ms['module_name']}\n{ms['summary']}")
        return "\n\n".join(parts) if parts else "（无模块摘要数据）"

    @staticmethod
    def _build_project_overview(gitnexus_data: dict, deepwiki_data: dict) -> str:
        """Build a brief project overview from available data."""
        parts: list[str] = []

        nodes = gitnexus_data.get("nodes", [])
        if nodes:
            file_count = sum(1 for n in nodes if n.get("label") == "File")
            func_count = sum(1 for n in nodes if n.get("label") == "Function")
            parts.append(f"代码图谱: {file_count} 个文件, {func_count} 个函数")

        doc = deepwiki_data.get("documentation", "")
        if doc:
            preview = doc[:500]
            parts.append(f"Wiki 概要: {preview}")

        return "\n".join(parts) if parts else "（无项目概览数据）"

    @staticmethod
    def _build_inter_module_deps(gitnexus_data: dict) -> str:
        """Extract cross-module dependency edges."""
        relationships = gitnexus_data.get("relationships", [])

        member_to_community: dict[str, str] = {}
        for edge in relationships:
            if edge.get("type") == "MEMBER_OF":
                member_to_community[edge["sourceId"]] = edge["targetId"]

        cross_deps: list[str] = []
        for edge in relationships:
            if edge.get("type") in ("CALLS", "IMPORTS", "DEPENDS_ON"):
                src_c = member_to_community.get(edge["sourceId"])
                tgt_c = member_to_community.get(edge["targetId"])
                if src_c and tgt_c and src_c != tgt_c:
                    cross_deps.append(f"{src_c} -> {tgt_c} ({edge.get('type')})")

        unique_deps = list(dict.fromkeys(cross_deps))
        return "\n".join(unique_deps[:30]) if unique_deps else "（无跨模块依赖数据）"

    @staticmethod
    def _build_process_data(gitnexus_data: dict) -> str:
        """Extract process/flow data from GitNexus."""
        nodes = gitnexus_data.get("nodes", [])
        processes = [n for n in nodes if n.get("label") == "Process"]
        if not processes:
            return "（无流程数据）"

        parts: list[str] = []
        for proc in processes[:10]:
            props = proc.get("properties", {})
            name = props.get("name", proc["id"])
            ptype = props.get("processType", "unknown")
            steps = props.get("stepCount", 0)
            parts.append(f"- {name} (类型: {ptype}, 步骤数: {steps})")

        return "\n".join(parts)

    @staticmethod
    def _build_cross_module_calls(gitnexus_data: dict) -> str:
        """Extract cross-module call relationships."""
        relationships = gitnexus_data.get("relationships", [])

        member_to_community: dict[str, str] = {}
        for edge in relationships:
            if edge.get("type") == "MEMBER_OF":
                member_to_community[edge["sourceId"]] = edge["targetId"]

        cross_calls: list[str] = []
        for edge in relationships:
            if edge.get("type") == "CALLS":
                src_c = member_to_community.get(edge["sourceId"])
                tgt_c = member_to_community.get(edge["targetId"])
                if src_c and tgt_c and src_c != tgt_c:
                    cross_calls.append(
                        f"{edge['sourceId']} ({src_c}) -> {edge['targetId']} ({tgt_c})"
                    )

        return "\n".join(cross_calls[:30]) if cross_calls else "（无跨模块调用数据）"

    @staticmethod
    def _build_key_files(gitnexus_data: dict) -> str:
        """Identify key files by edge count (high connectivity = important)."""
        nodes = gitnexus_data.get("nodes", [])
        relationships = gitnexus_data.get("relationships", [])

        edge_count: dict[str, int] = {}
        for edge in relationships:
            edge_count[edge["sourceId"]] = edge_count.get(edge["sourceId"], 0) + 1
            edge_count[edge["targetId"]] = edge_count.get(edge["targetId"], 0) + 1

        file_nodes = [n for n in nodes if n.get("label") in ("File", "Module")]
        ranked = sorted(
            file_nodes, key=lambda n: edge_count.get(n["id"], 0), reverse=True
        )

        parts: list[str] = []
        for node in ranked[:15]:
            props = node.get("properties", {})
            name = props.get("name", node["id"])
            count = edge_count.get(node["id"], 0)
            parts.append(f"- {name} (连接数: {count})")

        return "\n".join(parts) if parts else "（无重点文件数据）"

    @staticmethod
    def _build_call_graph(gitnexus_data: dict) -> str:
        """Format call graph edges as text."""
        relationships = gitnexus_data.get("relationships", [])
        call_edges = [
            e for e in relationships if e.get("type") in ("CALLS", "IMPORTS")
        ]

        parts: list[str] = []
        for edge in call_edges[:30]:
            parts.append(f"{edge['sourceId']} -> {edge['targetId']}")

        return "\n".join(parts) if parts else "（无调用图数据）"

    @staticmethod
    def _build_api_interfaces(gitnexus_data: dict) -> str:
        """Extract nodes that look like API endpoints or public interfaces."""
        nodes = gitnexus_data.get("nodes", [])

        api_nodes: list[str] = []
        for node in nodes:
            props = node.get("properties", {})
            name = props.get("name", "")
            label = node.get("label", "")
            if label == "Function" and any(
                kw in name.lower()
                for kw in ("route", "endpoint", "handler", "api", "view")
            ):
                api_nodes.append(f"- {name} ({label})")

        return (
            "\n".join(api_nodes[:20])
            if api_nodes
            else "（无接口数据，请参考模块摘要中的对外接口部分）"
        )

    @staticmethod
    def _truncate(text: str, max_chars: int) -> str:
        """Truncate text to max_chars to stay within token budget."""
        if len(text) <= max_chars:
            return text
        return text[:max_chars] + "\n...（已截断）"