"""Report generator -- takes module summaries + LLM client, generates each report file.

Each report is generated by:
1. Formatting the prompt template with context data
2. Calling the LLM
3. Saving the markdown output to data/outputs/{task_id}/XX-报告名.md
"""

import asyncio
import logging
import re
from collections.abc import Awaitable, Callable
from datetime import datetime, timezone
from pathlib import Path

try:
    import tiktoken

    _tiktoken_enc = tiktoken.get_encoding("cl100k_base")
except Exception:  # ImportError or encoding download failure
    _tiktoken_enc = None

from app.config import settings
from app.llm.base import BaseLLMClient, LLMResponse
from app.prompts.schemas import REPORT_FILE_MAP
from app.prompts.templates import (
    BUSINESS_FLOW_PROMPT,
    MODULE_MAP_PROMPT,
    REQUIREMENTS_PROMPT,
    SOURCE_READING_PROMPT,
    TEST_DESIGN_PROMPT,
    TRACEABILITY_PROMPT,
)

logger = logging.getLogger(__name__)

MAX_OUTPUT_TOKENS = 8192

_DATA_QUALITY_PREFIX: dict[str, str] = {
    "degraded": "注意：部分数据源不可用，请基于已有信息尽量推断\n\n",
    "poor": "注意：主要数据源均不可用，请基于模块摘要和常识进行推断分析\n\n",
}


class ReportGenerator:
    """Generates analysis report files from module summaries via LLM."""

    def __init__(
        self,
        llm_client: BaseLLMClient,
        output_dir: Path,
        task_id: str,
    ) -> None:
        self._llm = llm_client
        self._output_dir = output_dir
        self._task_id = task_id
        self._generated_files: list[str] = []
        self._status_override: str | None = None

    @property
    def generated_files(self) -> list[str]:
        return list(self._generated_files)

    @property
    def status_override(self) -> str | None:
        """Non-None when report generation decided to alter the final task status."""
        return self._status_override

    async def generate_all(
        self,
        module_summaries: list[dict],
        gitnexus_data: dict,
        deepwiki_data: dict,
        requirements_doc: str | None = None,
        design_doc: str | None = None,
        analysis_focus: str = "",
        prompt_content: str = "",
        on_report_done: Callable[[str, str, int], Awaitable[None]] | None = None,
        on_report_start: Callable[[str, int, int], Awaitable[None]] | None = None,
        on_report_failed: Callable[[str, str], Awaitable[None]] | None = None,
        max_concurrency: int = 1,
        data_quality: str = "good",
        use_streaming: bool = False,
    ) -> list[str]:
        """Generate all applicable reports and return list of filenames."""
        if not module_summaries:
            logger.warning(
                "No module summaries available for task %s -- "
                "skipping report generation (completed_with_warnings)",
                self._task_id,
                extra={"task_id": self._task_id},
            )
            self._status_override = "completed_with_warnings"
            return self._generated_files

        summaries_text = self._format_summaries(module_summaries)

        content_prefix = _DATA_QUALITY_PREFIX.get(data_quality, "")

        if prompt_content:
            content_prefix += (
                f"## 用户自定义分析提示词\n{prompt_content[:4000]}\n\n"
                "请参考以上分析方法论和要求展开分析。\n\n"
            )
        elif analysis_focus:
            content_prefix += (
                f"## 用户分析目标\n{analysis_focus}\n\n"
                "请围绕此目标重点展开分析。\n\n"
            )

        # Build all applicable report coroutines then run them with concurrency control
        report_tasks: list[tuple[str, Awaitable]] = [
            (
                "module_map",
                self._generate_report(
                    report_type="module_map",
                    prompt=content_prefix + MODULE_MAP_PROMPT.format(
                        project_overview=self._build_project_overview(gitnexus_data, deepwiki_data),
                        module_summaries=summaries_text,
                        inter_module_deps=self._build_inter_module_deps(gitnexus_data),
                    ),
                    on_report_done=on_report_done,

                    use_streaming=use_streaming,
                ),
            ),
            (
                "business_flow",
                self._generate_report(
                    report_type="business_flow",
                    prompt=content_prefix + BUSINESS_FLOW_PROMPT.format(
                        module_summaries=summaries_text,
                        process_data=self._build_process_data(gitnexus_data, deepwiki_data),
                        cross_module_calls=self._build_cross_module_calls(gitnexus_data, deepwiki_data),
                    ),
                    on_report_done=on_report_done,

                    use_streaming=use_streaming,
                ),
            ),
            (
                "source_reading",
                self._generate_report(
                    report_type="source_reading",
                    prompt=content_prefix + SOURCE_READING_PROMPT.format(
                        module_summaries=summaries_text,
                        key_files=self._build_key_files(gitnexus_data, deepwiki_data),
                        call_graph=self._build_call_graph(gitnexus_data, deepwiki_data),
                    ),
                    on_report_done=on_report_done,

                    use_streaming=use_streaming,
                ),
            ),
            (
                "test_design",
                self._generate_report(
                    report_type="test_design",
                    prompt=content_prefix + TEST_DESIGN_PROMPT.format(
                        module_summaries=summaries_text,
                        business_flows=self._build_process_data(gitnexus_data, deepwiki_data),
                        api_interfaces=self._build_api_interfaces(gitnexus_data, deepwiki_data),
                    ),
                    on_report_done=on_report_done,

                    use_streaming=use_streaming,
                ),
            ),
        ]

        # Optional reports: only if requirements/design docs provided
        if requirements_doc:
            report_tasks.append((
                "requirements",
                self._generate_report(
                    report_type="requirements",
                    prompt=content_prefix + REQUIREMENTS_PROMPT.format(
                        requirements_doc=self._truncate(requirements_doc, 5000),
                        design_doc=self._truncate(design_doc or "（未提供设计文档）", 5000),
                        module_summaries=summaries_text,
                    ),
                    on_report_done=on_report_done,

                    use_streaming=use_streaming,
                ),
            ))

        if requirements_doc and design_doc:
            report_tasks.append((
                "traceability",
                self._generate_report(
                    report_type="traceability",
                    prompt=content_prefix + TRACEABILITY_PROMPT.format(
                        requirements_items=self._truncate(requirements_doc, 3000),
                        design_modules=self._truncate(design_doc, 3000),
                        module_summaries=summaries_text,
                        call_relations=self._build_call_graph(gitnexus_data, deepwiki_data),
                    ),
                    on_report_done=on_report_done,

                    use_streaming=use_streaming,
                ),
            ))

        sem = asyncio.Semaphore(max_concurrency)
        total = len(report_tasks)

        async def _guarded(idx: int, rtype: str, coro: Awaitable) -> None:
            async with sem:
                if on_report_start is not None:
                    await on_report_start(rtype, idx + 1, total)
                return await coro

        results = await asyncio.gather(
            *[_guarded(i, rtype, coro) for i, (rtype, coro) in enumerate(report_tasks)],
            return_exceptions=True,
        )

        for i, r in enumerate(results):
            if isinstance(r, BaseException):
                report_type = report_tasks[i][0]
                error_message = str(r)
                logger.error(
                    "Report generation failed in parallel: %s",
                    r,
                    extra={"task_id": self._task_id},
                )
                self._status_override = "completed_with_warnings"
                if on_report_failed is not None:
                    await on_report_failed(report_type, error_message)

        return self._generated_files

    async def _generate_report(
        self,
        report_type: str,
        prompt: str,
        on_report_done: Callable[[str, str, int], Awaitable[None]] | None = None,
        use_streaming: bool = False,
    ) -> None:
        """Generate a single report and save to disk."""
        filename = REPORT_FILE_MAP.get(report_type)
        if not filename:
            logger.warning("Unknown report type: %s", report_type)
            return

        try:
            messages = [{"role": "user", "content": prompt}]

            # Use streaming when requested AND the client has a real stream_complete
            # (not the base class fallback that just wraps complete()).
            has_real_streaming = (
                type(self._llm).stream_complete is not BaseLLMClient.stream_complete
            )

            if use_streaming and has_real_streaming:
                full_content = await self._llm.stream_complete_collected(
                    messages=messages,
                    max_tokens=min(MAX_OUTPUT_TOKENS, settings.llm_max_output_tokens),
                    temperature=0.3,
                )

                full_content = self._validate_report_structure(full_content, report_type)
                total_tokens = BaseLLMClient.estimate_tokens(full_content)
                # Use a placeholder model name since streaming doesn't return model info
                model_name = type(self._llm).__name__

                now = datetime.now(timezone.utc).isoformat()
                header = (
                    f"---\n"
                    f"report_type: {report_type}\n"
                    f"task_id: {self._task_id}\n"
                    f"generated_at: {now}\n"
                    f"model: {model_name}\n"
                    f"tokens: {total_tokens}\n"
                    f"---\n\n"
                )

                filepath = self._output_dir / filename
                content = header + full_content
                await asyncio.to_thread(filepath.write_text, content, "utf-8")
                self._generated_files.append(filename)

                if on_report_done is not None:
                    await on_report_done(report_type, filename, total_tokens)

                logger.info(
                    "Report %s generated (streaming): %s (~%d tokens)",
                    report_type,
                    filename,
                    total_tokens,
                    extra={"task_id": self._task_id},
                )
            else:
                response: LLMResponse = await self._llm.complete(
                    messages=messages,
                    max_tokens=min(MAX_OUTPUT_TOKENS, settings.llm_max_output_tokens),
                    temperature=0.3,
                )

                validated_content = self._validate_report_structure(response.content, report_type)
                # Prepend metadata header
                now = datetime.now(timezone.utc).isoformat()
                header = (
                    f"---\n"
                    f"report_type: {report_type}\n"
                    f"task_id: {self._task_id}\n"
                    f"generated_at: {now}\n"
                    f"model: {response.model}\n"
                    f"tokens: {response.usage.get('total_tokens', 0)}\n"
                    f"---\n\n"
                )

                filepath = self._output_dir / filename
                content = header + validated_content
                await asyncio.to_thread(filepath.write_text, content, "utf-8")
                self._generated_files.append(filename)

                total_tokens = response.usage.get("total_tokens", 0)
                if on_report_done is not None:
                    await on_report_done(report_type, filename, total_tokens)

                logger.info(
                    "Report %s generated: %s (%d tokens)",
                    report_type,
                    filename,
                    response.usage.get("total_tokens", 0),
                    extra={"task_id": self._task_id},
                )

        except Exception as exc:
            logger.exception("Report generation failed for %s: %s", report_type, exc, extra={"task_id": self._task_id})
            raise

    # ------------------------------------------------------------------
    # Context builders -- extract relevant data for each prompt
    # ------------------------------------------------------------------

    @staticmethod
    def _format_summaries(module_summaries: list[dict]) -> str:
        """Format module summaries for inclusion in report prompts."""
        parts: list[str] = []
        for ms in module_summaries:
            parts.append(f"### {ms['module_name']}\n{ms['summary']}")
        return "\n\n".join(parts) if parts else "（无模块摘要数据）"

    @staticmethod
    def _build_project_overview(gitnexus_data: dict, deepwiki_data: dict) -> str:
        """Build a brief project overview from available data."""
        parts: list[str] = []

        nodes = gitnexus_data.get("nodes", [])
        if nodes:
            file_count = sum(1 for n in nodes if n.get("label") == "File")
            func_count = sum(1 for n in nodes if n.get("label") == "Function")
            parts.append(f"代码图谱: {file_count} 个文件, {func_count} 个函数")

        doc = deepwiki_data.get("documentation", "")
        if doc:
            preview = doc[:500]
            parts.append(f"Wiki 概要: {preview}")

        return "\n".join(parts) if parts else "（无项目概览数据）"

    @staticmethod
    def _build_inter_module_deps(gitnexus_data: dict) -> str:
        """Extract cross-module dependency edges."""
        relationships = gitnexus_data.get("relationships", [])

        member_to_community: dict[str, str] = {}
        for edge in relationships:
            if edge.get("type") == "MEMBER_OF":
                member_to_community[edge["sourceId"]] = edge["targetId"]

        cross_deps: list[str] = []
        for edge in relationships:
            if edge.get("type") in ("CALLS", "IMPORTS", "DEPENDS_ON"):
                src_c = member_to_community.get(edge["sourceId"])
                tgt_c = member_to_community.get(edge["targetId"])
                if src_c and tgt_c and src_c != tgt_c:
                    cross_deps.append(f"{src_c} -> {tgt_c} ({edge.get('type')})")

        unique_deps = list(dict.fromkeys(cross_deps))
        return "\n".join(unique_deps[:30]) if unique_deps else "（无跨模块依赖数据）"

    @staticmethod
    def _extract_wiki_section(deepwiki_data: dict, keywords: list[str], max_chars: int = 2000) -> str:
        """Extract relevant sections from DeepWiki documentation by keyword matching."""
        doc = deepwiki_data.get("documentation", "")
        if not doc:
            return ""

        paragraphs = doc.split("\n\n")
        matched: list[str] = []
        for para in paragraphs:
            lower = para.lower()
            if any(kw.lower() in lower for kw in keywords):
                matched.append(para)

        combined = "\n\n".join(matched)
        if len(combined) > max_chars:
            combined = combined[:max_chars] + "\n...（已截断）"
        return combined

    @staticmethod
    def _build_process_data(gitnexus_data: dict, deepwiki_data: dict) -> str:
        """Extract process/flow data from GitNexus, supplemented by DeepWiki."""
        nodes = gitnexus_data.get("nodes", [])
        processes = [n for n in nodes if n.get("label") == "Process"]

        parts: list[str] = []
        if processes:
            for proc in processes[:10]:
                props = proc.get("properties", {})
                name = props.get("name", proc["id"])
                ptype = props.get("processType", "unknown")
                steps = props.get("stepCount", 0)
                parts.append(f"- {name} (类型: {ptype}, 步骤数: {steps})")
        else:
            wiki_section = ReportGenerator._extract_wiki_section(
                deepwiki_data,
                keywords=["flow", "process", "workflow", "流程", "步骤", "pipeline"],
            )
            if wiki_section:
                parts.append(f"[Wiki 流程信息]\n{wiki_section}")

        return "\n".join(parts) if parts else "（无流程数据）"

    @staticmethod
    def _build_cross_module_calls(gitnexus_data: dict, deepwiki_data: dict) -> str:
        """Extract cross-module call relationships, supplemented by DeepWiki."""
        relationships = gitnexus_data.get("relationships", [])

        member_to_community: dict[str, str] = {}
        for edge in relationships:
            if edge.get("type") == "MEMBER_OF":
                member_to_community[edge["sourceId"]] = edge["targetId"]

        cross_calls: list[str] = []
        for edge in relationships:
            if edge.get("type") == "CALLS":
                src_c = member_to_community.get(edge["sourceId"])
                tgt_c = member_to_community.get(edge["targetId"])
                if src_c and tgt_c and src_c != tgt_c:
                    cross_calls.append(
                        f"{edge['sourceId']} ({src_c}) -> {edge['targetId']} ({tgt_c})"
                    )

        parts = cross_calls[:30]

        wiki_section = ReportGenerator._extract_wiki_section(
            deepwiki_data,
            keywords=["module", "interaction", "integration", "模块", "集成", "交互"],
        )
        if wiki_section:
            parts.append(f"\n[Wiki 模块交互信息]\n{wiki_section}")

        return "\n".join(parts) if parts else "（无跨模块调用数据）"

    @staticmethod
    def _build_key_files(gitnexus_data: dict, deepwiki_data: dict) -> str:
        """Identify key files by edge count, enriched with DEFINES detail."""
        nodes = gitnexus_data.get("nodes", [])
        relationships = gitnexus_data.get("relationships", [])
        nodes_by_id = {n["id"]: n for n in nodes}

        edge_count: dict[str, int] = {}
        for edge in relationships:
            edge_count[edge["sourceId"]] = edge_count.get(edge["sourceId"], 0) + 1
            edge_count[edge["targetId"]] = edge_count.get(edge["targetId"], 0) + 1

        file_defines: dict[str, list[str]] = {}
        for edge in relationships:
            if edge.get("type") in ("DEFINES", "CONTAINS"):
                src = edge["sourceId"]
                tgt_node = nodes_by_id.get(edge["targetId"], {})
                tgt_label = tgt_node.get("label", "")
                tgt_name = tgt_node.get("properties", {}).get("name", edge["targetId"])
                if tgt_label in ("Function", "Class", "Struct"):
                    file_defines.setdefault(src, []).append(f"{tgt_label}:{tgt_name}")

        file_nodes = [n for n in nodes if n.get("label") in ("File", "Module")]
        ranked = sorted(
            file_nodes, key=lambda n: edge_count.get(n["id"], 0), reverse=True
        )

        parts: list[str] = []
        for node in ranked[:15]:
            props = node.get("properties", {})
            name = props.get("name", node["id"])
            count = edge_count.get(node["id"], 0)
            defines = file_defines.get(node["id"], [])
            detail = f", 定义: {', '.join(defines[:5])}" if defines else ""
            parts.append(f"- {name} (连接数: {count}{detail})")

        if len(file_nodes) < 5 and deepwiki_data.get("documentation"):
            parts.append("\n[注意: GitNexus 文件节点较少，DeepWiki 文档可供深入阅读参考]")

        return "\n".join(parts) if parts else "（无重点文件数据）"

    @staticmethod
    def _build_call_graph(gitnexus_data: dict, deepwiki_data: dict) -> str:
        """Format call graph edges as text, falling back to DEFINES when CALLS are absent."""
        relationships = gitnexus_data.get("relationships", [])
        call_edges = [
            e for e in relationships if e.get("type") in ("CALLS", "IMPORTS")
        ]

        parts: list[str] = []
        for edge in call_edges[:30]:
            parts.append(f"{edge['sourceId']} -> {edge['targetId']}")

        if not call_edges:
            nodes_by_id = {n["id"]: n for n in gitnexus_data.get("nodes", [])}
            define_edges = [
                e for e in relationships if e.get("type") in ("DEFINES", "CONTAINS")
            ]
            if define_edges:
                parts.append("[定义关系（CALLS 数据不可用，以定义关系代替）]")
                for edge in define_edges[:30]:
                    src_name = nodes_by_id.get(edge["sourceId"], {}).get("properties", {}).get("name", edge["sourceId"])
                    tgt_node = nodes_by_id.get(edge["targetId"], {})
                    tgt_name = tgt_node.get("properties", {}).get("name", edge["targetId"])
                    tgt_label = tgt_node.get("label", "")
                    parts.append(f"{src_name} -[{edge['type']}]-> {tgt_label}:{tgt_name}")

        if len(call_edges) < 5 and deepwiki_data.get("documentation"):
            parts.append("\n[注意: 调用图数据较少，DeepWiki 文档可供深入阅读参考]")

        return "\n".join(parts) if parts else "（无调用图数据）"

    @staticmethod
    def _build_api_interfaces(gitnexus_data: dict, deepwiki_data: dict) -> str:
        """Extract API endpoints from GitNexus, supplemented by DeepWiki API sections."""
        nodes = gitnexus_data.get("nodes", [])

        api_nodes: list[str] = []
        for node in nodes:
            props = node.get("properties", {})
            name = props.get("name", "")
            label = node.get("label", "")
            if label == "Function" and any(
                kw in name.lower()
                for kw in ("route", "endpoint", "handler", "api", "view")
            ):
                api_nodes.append(f"- {name} ({label})")

        parts = api_nodes[:20]

        wiki_section = ReportGenerator._extract_wiki_section(
            deepwiki_data,
            keywords=["api", "endpoint", "interface", "接口", "路由", "route"],
        )
        if wiki_section:
            parts.append(f"\n[Wiki API 信息]\n{wiki_section}")

        return (
            "\n".join(parts)
            if parts
            else "（无接口数据，请参考模块摘要中的对外接口部分）"
        )

    @staticmethod
    def _validate_report_structure(content: str, report_type: str) -> str:
        """Append a warning line if required structural elements are missing."""
        missing: list[str] = []

        if not re.search(r"\|.+\|.+\|", content):
            missing.append("Markdown表格")

        if report_type in ("module_map", "business_flow") and "```mermaid" not in content:
            missing.append("Mermaid图")

        if missing:
            logger.warning(
                "Report %s is missing structural elements: %s",
                report_type,
                "、".join(missing),
            )
            return content + "\n\n> ⚠ 本报告格式未完全符合规范，部分结构化内容可能缺失"

        return content

    @staticmethod
    def _truncate(text: str, max_chars: int) -> str:
        """Truncate text to stay within token budget.

        When tiktoken is available, *max_chars* is treated as a **token** limit
        and the text is truncated at a token boundary.  Otherwise we fall back
        to approximating tokens as ``len(text) // 4`` and cutting by character
        count.
        """
        if _tiktoken_enc is not None:
            tokens = _tiktoken_enc.encode(text)
            if len(tokens) <= max_chars:
                return text
            truncated_tokens = tokens[:max_chars]
            result = _tiktoken_enc.decode(truncated_tokens)
            logger.info(
                "Truncated context: %d -> %d tokens",
                len(tokens),
                len(truncated_tokens),
            )
            return result + "\n...（已截断）"

        # Fallback: approximate tokens as chars / 4
        approx_tokens = len(text) // 4
        if approx_tokens <= max_chars:
            return text
        char_limit = max_chars * 4
        result = text[:char_limit]
        logger.info(
            "Truncated context (char approx): ~%d -> ~%d tokens",
            approx_tokens,
            max_chars,
        )
        return result + "\n...（已截断）"