"""Report generator -- takes module summaries + LLM client, generates each report file.

Each report is generated by:
1. Formatting the prompt template with context data
2. Calling the LLM
3. Saving the markdown output to data/outputs/{task_id}/XX-报告名.md

F-WORKSPACE-GITNEXUS-ANALYSIS-TASK-REDESIGN adds a plan-driven path that
generates each report section-by-section, retries empty/truncated output,
and writes a ``report_manifest.json`` so the workspace pipeline can mark
reports as ``completed``, ``partial`` or ``failed`` instead of silently
shipping blank files.
"""

import asyncio
import json
import logging
import re
from collections.abc import Awaitable, Callable
from datetime import datetime, timezone
from pathlib import Path

try:
    import tiktoken

    _tiktoken_enc = tiktoken.get_encoding("cl100k_base")
except Exception:  # ImportError or encoding download failure
    _tiktoken_enc = None

from app.config import settings
from app.llm.base import BaseLLMClient, LLMEmptyOutputError, LLMResponse
from app.prompts.schemas import REPORT_FILE_MAP
from app.schemas.workspace_analysis import AnalysisPlan, ReportSpec, ScopePreview
from app.prompts.templates import (
    BUSINESS_FLOW_PROMPT,
    MODULE_MAP_PROMPT,
    REQUIREMENTS_PROMPT,
    SOURCE_READING_PROMPT,
    TEST_DESIGN_PROMPT,
    TRACEABILITY_PROMPT,
)

logger = logging.getLogger(__name__)

MAX_OUTPUT_TOKENS = 8192
MAX_SOURCE_BYTES = 50_000

_SOURCE_EXTS = frozenset({
    ".py", ".js", ".ts", ".tsx", ".jsx", ".go", ".rs", ".java", ".kt",
    ".c", ".cpp", ".h", ".hpp", ".cs", ".rb", ".php", ".swift", ".vue",
    ".sh", ".bat", ".sql", ".yaml", ".yml", ".toml", ".json",
})

_DATA_QUALITY_PREFIX: dict[str, str] = {
    "degraded": "注意：部分数据源不可用，请基于已有信息尽量推断\n\n",
    "poor": "注意：主要数据源均不可用，请基于模块摘要和常识进行推断分析\n\n",
}

_TABLE_RE = re.compile(r"\|.+\|.+\|")
_MERMAID_RE = re.compile(r"```mermaid\b")
_MERMAID_REQUIRED_TYPES = frozenset({"module_map", "business_flow"})


def _validate_report_structure(content: str, report_type: str) -> str:
    """Check LLM output for required structural elements.

    Returns the content with a warning appended if structure is incomplete.
    Non-blocking: never raises.
    """
    missing: list[str] = []

    if not _TABLE_RE.search(content):
        missing.append("Markdown 表格")

    if report_type in _MERMAID_REQUIRED_TYPES and not _MERMAID_RE.search(content):
        missing.append("Mermaid 图")

    if not missing:
        return content

    logger.warning(
        "Report %s missing structural elements: %s",
        report_type,
        ", ".join(missing),
    )
    warning = (
        "\n\n> ⚠ 本报告格式未完全符合规范，"
        f"缺失: {', '.join(missing)}"
    )
    return content + warning


class ReportGenerator:
    """Generates analysis report files from module summaries via LLM."""

    def __init__(
        self,
        llm_client: BaseLLMClient,
        output_dir: Path,
        task_id: str,
    ) -> None:
        self._llm = llm_client
        self._output_dir = output_dir
        self._task_id = task_id
        self._generated_files: list[str] = []
        self._status_override: str | None = None

    @property
    def generated_files(self) -> list[str]:
        return list(self._generated_files)

    @property
    def status_override(self) -> str | None:
        """Non-None when report generation decided to alter the final task status."""
        return self._status_override

    # ------------------------------------------------------------------
    # F-WORKSPACE-GITNEXUS-ANALYSIS-TASK-REDESIGN
    # Plan-driven path: section-by-section LLM calls + programmatic
    # Markdown assembly + per-section retry on empty / truncated output.
    # ------------------------------------------------------------------

    async def generate_from_plan(
        self,
        *,
        plan: AnalysisPlan,
        scope_preview: ScopePreview | None,
        analysis_units: list[dict],
        evidence_cards: list,
        module_summaries: list[dict],
        gitnexus_data: dict,
        deepwiki_data: dict,
        requirements_doc: str | None = None,
        design_doc: str | None = None,
        on_report_done: Callable[[str, str, int], Awaitable[None]] | None = None,
        on_report_start: Callable[[str, int, int], Awaitable[None]] | None = None,
        on_report_failed: Callable[[str, str], Awaitable[None]] | None = None,
        sem: asyncio.Semaphore | None = None,
        data_quality: str = "good",
        repo_path: str = "",
    ) -> list[dict]:
        """Generate every enabled report in *plan* using small LLM calls.

        *sem* is the pipeline-owned global LLM semaphore.  All section-level
        LLM calls share this budget so total concurrent calls never exceed
        ``LLM_MAX_CONCURRENCY``.  If not provided a unit semaphore is used
        (concurrency=1, safe fallback).

        Returns a list of manifest entries (also persisted as
        ``report_manifest.json`` in the output dir).
        """
        enabled = [r for r in plan.reports if r.enabled]
        if not enabled:
            return []

        sem = sem if sem is not None else asyncio.Semaphore(1)
        total = len(enabled)

        # Context blob reused across reports (small — we cap each piece).
        common_context = {
            "analysis_objects": [
                {"id": o.id, "text": o.text, "kind": o.kind, "priority": o.priority}
                for o in plan.analysis_objects
            ],
            "scope_warnings": (scope_preview.warnings if scope_preview else []),
            "gitnexus_available": (
                scope_preview.gitnexus_available if scope_preview else True
            ),
            "data_quality": data_quality,
            "user_guidance": plan.user_guidance,
            "focus": plan.focus.model_dump(),
            "limits": plan.llm_limits.model_dump(),
            "has_requirements": bool(requirements_doc),
            "has_design": bool(design_doc),
            "requirements_doc_excerpt": (requirements_doc or "")[:3000],
            "design_doc_excerpt": (design_doc or "")[:3000],
            "module_summaries": module_summaries,
        }

        manifest_entries: list[dict] = []

        async def _run_one(idx: int, spec: ReportSpec) -> dict:
            if on_report_start is not None:
                await on_report_start(spec.template_id, idx + 1, total)
            entry = await self._generate_plan_report(
                spec=spec,
                plan=plan,
                common_context=common_context,
                analysis_units=analysis_units,
                evidence_cards=evidence_cards,
                sem=sem,
            )
            if entry["status"] == "completed":
                if on_report_done is not None:
                    await on_report_done(
                        spec.template_id,
                        entry["filename"],
                        entry["metadata"].get("char_count", 0),
                    )
            else:
                if on_report_failed is not None:
                    await on_report_failed(
                        spec.template_id, entry.get("error") or "(unknown)",
                    )
            return entry

        results = await asyncio.gather(
            *[_run_one(i, spec) for i, spec in enumerate(enabled)],
            return_exceptions=True,
        )
        for r in results:
            if isinstance(r, BaseException):
                logger.exception("Plan-driven report failed: %s", r)
                manifest_entries.append({
                    "report_type": "unknown",
                    "filename": "",
                    "status": "failed",
                    "error": str(r),
                    "metadata": {},
                })
            else:
                manifest_entries.append(r)

        any_completed = any(e["status"] == "completed" for e in manifest_entries)
        any_failed = any(e["status"] != "completed" for e in manifest_entries)
        if any_completed and any_failed:
            self._status_override = "completed_with_warnings"
        elif not any_completed:
            self._status_override = "failed"

        # Persist manifest for workspace_pipeline._harvest_reports.
        manifest = {
            "version": "workspace-report-manifest-v1",
            "task_id": self._task_id,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "reports": manifest_entries,
        }
        manifest_path = self._output_dir / "report_manifest.json"
        try:
            await asyncio.to_thread(
                manifest_path.write_text,
                json.dumps(manifest, ensure_ascii=False, indent=2),
                "utf-8",
            )
        except Exception as exc:
            logger.warning("Failed to write report manifest: %s", exc)

        return manifest_entries

    async def _generate_plan_report(
        self,
        *,
        spec: ReportSpec,
        plan: AnalysisPlan,
        common_context: dict,
        analysis_units: list[dict],
        evidence_cards: list,
        sem: asyncio.Semaphore,
    ) -> dict:
        """Build one report file from small section calls, sections run in parallel."""
        sections_blueprint = _SECTION_BLUEPRINTS.get(spec.template_id)
        if sections_blueprint is None:
            sections_blueprint = _default_sections_for(spec)

        filename = _plan_report_filename(spec)
        section_outputs: list[tuple[str, str, str]] = []  # (heading, body, status)
        any_failure = False

        async def _do_section(section_idx: int, section: dict) -> tuple[str, str, str]:
            body, status = await self._render_section(
                spec=spec,
                section=section,
                plan=plan,
                common_context=common_context,
                analysis_units=analysis_units,
                evidence_cards=evidence_cards,
                section_idx=section_idx,
                sem=sem,
            )
            return (section["heading"], body, status)

        raw_results = await asyncio.gather(
            *[_do_section(i, s) for i, s in enumerate(sections_blueprint)],
            return_exceptions=True,
        )
        for r in raw_results:
            if isinstance(r, BaseException):
                logger.exception("Section generation failed: %s", r)
                section_outputs.append(("(section error)", str(r), "failed"))
                any_failure = True
            else:
                section_outputs.append(r)
                if r[2] != "completed":
                    any_failure = True

        # Assemble the file programmatically per §13.1.
        now = datetime.now(timezone.utc).isoformat()
        header = (
            f"---\n"
            f"report_type: {spec.template_id}\n"
            f"template_id: {spec.template_id}\n"
            f"task_id: {self._task_id}\n"
            f"generated_at: {now}\n"
            f"plan_version: {plan.version}\n"
            f"---\n\n"
        )
        body_parts: list[str] = [f"# {spec.title}\n"]
        body_parts.append("> 本报告由小段 LLM 调用组装而成。证据不足处会显式标记 `待验证`。\n")
        if not common_context.get("gitnexus_available", True):
            body_parts.append("> ⚠ GitNexus 图谱不可用，已退回到本地搜索结果。\n")
        for heading, body, status in section_outputs:
            body_parts.append(f"\n## {heading}\n")
            if status == "completed":
                body_parts.append(body.rstrip() + "\n")
            elif status == "partial":
                body_parts.append(body.rstrip() + "\n\n> ⚠ 该小节内容不足，已重试后仍未达标。\n")
            else:
                body_parts.append(
                    "> ❌ 本小节生成失败：" + (body or "LLM 未返回内容") + "\n"
                )

        full_content = header + "\n".join(body_parts)
        filepath = self._output_dir / filename
        try:
            await asyncio.to_thread(filepath.write_text, full_content, "utf-8")
            self._generated_files.append(filename)
        except Exception as exc:
            logger.exception("Failed to write report %s: %s", filename, exc)
            return {
                "report_type": spec.template_id,
                "template_id": spec.template_id,
                "filename": filename,
                "title": spec.title,
                "status": "failed",
                "error": f"write failed: {exc}",
                "metadata": {},
            }

        status = "failed" if not any(s == "completed" for _, _, s in section_outputs) else (
            "partial" if any_failure else "completed"
        )
        return {
            "report_type": spec.template_id,
            "template_id": spec.template_id,
            "filename": filename,
            "title": spec.title,
            "status": status,
            "error": None if status == "completed" else "部分小节生成不足或失败",
            "metadata": {
                "section_count": len(section_outputs),
                "completed_sections": sum(1 for _, _, s in section_outputs if s == "completed"),
                "char_count": sum(len(b) for _, b, _ in section_outputs),
            },
        }

    async def _render_section(
        self,
        *,
        spec: ReportSpec,
        section: dict,
        plan: AnalysisPlan,
        common_context: dict,
        analysis_units: list[dict],
        evidence_cards: list,
        section_idx: int,
        sem: asyncio.Semaphore,
    ) -> tuple[str, str]:
        """Call the LLM for a single section, retrying once on empty output.

        Returns ``(body, status)`` where status ∈ {completed, partial, failed}.
        """
        # Pick a bounded slice of evidence relevant to the section.  We
        # currently use the whole unit list rounded-robin; real signal
        # comes from the LLM prompt itself.
        relevant_cards = []
        card_cap = plan.llm_limits.max_cards_per_report_section
        unit_iters = [iter(u.get("cards", [])) for u in analysis_units]
        while len(relevant_cards) < card_cap and unit_iters:
            exhausted = []
            for i, it in enumerate(unit_iters):
                if len(relevant_cards) >= card_cap:
                    break
                card = next(it, None)
                if card is None:
                    exhausted.append(i)
                else:
                    relevant_cards.append(card)
            for i in reversed(exhausted):
                unit_iters.pop(i)

        evidence_md = "\n\n".join(c.to_markdown() for c in relevant_cards) or "（未找到证据卡）"
        unit_summary = "\n".join(
            f"- {u.get('title', '')}" for u in analysis_units
        ) or "（无分析单元）"
        max_chars = plan.llm_limits.max_output_chars_per_section
        focus_active = ", ".join(k for k, v in plan.focus.model_dump().items() if v) or "无"

        guidance = (plan.user_guidance or "")[:1500]

        prompt = (
            "你是资深代码分析与测试专家。请严格基于提供的证据卡撰写一份报告小节，"
            "禁止编造文件名、函数名或调用关系。证据不足处必须显式写"
            "“数据不足，请验证”，并标注 `待验证`。\n\n"
            f"## 报告：{spec.title}\n"
            f"## 当前小节：{section['heading']}\n"
            f"### 写作要点\n{section['instructions']}\n\n"
            f"### 输出约束\n- 字数控制在 {max_chars} 字以内\n"
            "- 优先使用 Markdown 表格/代码块/调用链\n"
            "- 不要重复报告标题或元信息\n"
            "- 重要结论必须附带证据来源（文件或符号）\n"
        )
        if focus_active:
            prompt += f"\n### 焦点方向\n{focus_active}\n"
        if guidance:
            prompt += f"\n### 用户附加说明（仅作风格补充）\n{guidance}\n"
        if section.get("requires_sfmea"):
            prompt += (
                "\n### 强制要求\n本小节必须包含 SFMEA 表格，列标题为："
                "功能/流程 | 故障模式 | 触发条件 | 异常注入点 | 异常传播路径 | "
                "影响 | 可观测现象 | 严重度 | 发生概率 | 检测难度 | 建议测试\n"
            )
        if section.get("requires_mermaid"):
            prompt += (
                "\n### 强制要求\n本小节必须包含至少一段 Mermaid 序列图或流程图，"
                "用 ```mermaid 代码块包裹。\n"
            )
        prompt += (
            f"\n## 分析单元概览\n{unit_summary}\n"
            f"\n## 证据卡（最多 {card_cap} 条）\n{evidence_md}\n"
        )

        messages = [{"role": "user", "content": prompt}]
        budget_tokens = min(
            settings.llm_max_output_tokens, max(800, max_chars * 2),
        )
        min_chars = max(60, section.get("min_chars", 80))

        has_real_streaming = (
            type(self._llm).stream_complete is not BaseLLMClient.stream_complete
        )
        retries = max(0, plan.llm_limits.retry_empty_output) + 1
        last_error: str | None = None
        body = ""
        for attempt in range(retries):
            try:
                async with sem:
                    if has_real_streaming:
                        body = await self._llm.stream_complete_collected(
                            messages=messages,
                            max_tokens=budget_tokens,
                            temperature=0.3,
                            min_chars=min_chars,
                            retry_on_empty=False,
                            max_retries=0,
                        )
                    else:
                        resp = await self._llm.complete(
                            messages=messages, max_tokens=budget_tokens, temperature=0.3,
                        )
                        body = resp.content
                if _section_is_invalid(body, min_chars=min_chars, section=section):
                    raise LLMEmptyOutputError("section content failed structural validation")
                return body.strip(), "completed"
            except LLMEmptyOutputError as exc:
                last_error = str(exc)
                logger.warning(
                    "Section '%s' empty/invalid on attempt %d/%d: %s",
                    section["heading"], attempt + 1, retries, exc,
                )
            except Exception as exc:
                last_error = str(exc)
                logger.exception(
                    "Section '%s' LLM call failed on attempt %d/%d", section["heading"], attempt + 1, retries,
                )
                break

        if body and len(body.strip()) >= 20:
            return body.strip(), "partial"
        return (last_error or "LLM 返回为空"), "failed"


    async def generate_all(
        self,
        module_summaries: list[dict],
        gitnexus_data: dict,
        deepwiki_data: dict,
        requirements_doc: str | None = None,
        design_doc: str | None = None,
        analysis_focus: str = "",
        prompt_content: str = "",
        on_report_done: Callable[[str, str, int], Awaitable[None]] | None = None,
        on_report_start: Callable[[str, int, int], Awaitable[None]] | None = None,
        on_report_failed: Callable[[str, str], Awaitable[None]] | None = None,
        sem: asyncio.Semaphore | None = None,
        data_quality: str = "good",
        use_streaming: bool = False,
        repo_path: str = "",
    ) -> list[str]:
        """Generate all applicable reports and return list of filenames."""
        if not module_summaries:
            logger.warning(
                "No module summaries available for task %s -- "
                "skipping report generation (completed_with_warnings)",
                self._task_id,
                extra={"task_id": self._task_id},
            )
            self._status_override = "completed_with_warnings"
            return self._generated_files

        summaries_text = self._format_summaries(module_summaries)

        content_prefix = _DATA_QUALITY_PREFIX.get(data_quality, "")

        if prompt_content:
            content_prefix += (
                f"## 用户自定义分析提示词\n{prompt_content[:4000]}\n\n"
                "请参考以上分析方法论和要求展开分析。\n\n"
            )
        elif analysis_focus:
            content_prefix += (
                f"## 用户分析目标\n{analysis_focus}\n\n"
                "请围绕此目标重点展开分析。\n\n"
            )

        source_code = await asyncio.to_thread(
            self._read_source_for_key_files, repo_path, gitnexus_data,
        ) if repo_path else "（无源码路径）"

        # Build all applicable report coroutines then run them with concurrency control
        report_tasks: list[tuple[str, Awaitable]] = [
            (
                "module_map",
                self._generate_report(
                    report_type="module_map",
                    prompt=content_prefix + MODULE_MAP_PROMPT.format(
                        project_overview=self._build_project_overview(gitnexus_data, deepwiki_data),
                        module_summaries=summaries_text,
                        inter_module_deps=self._build_inter_module_deps(gitnexus_data),
                    ),
                    on_report_done=on_report_done,

                    use_streaming=use_streaming,
                ),
            ),
            (
                "business_flow",
                self._generate_report(
                    report_type="business_flow",
                    prompt=content_prefix + BUSINESS_FLOW_PROMPT.format(
                        module_summaries=summaries_text,
                        process_data=self._build_process_data(gitnexus_data, deepwiki_data),
                        cross_module_calls=self._build_cross_module_calls(gitnexus_data, deepwiki_data),
                        source_code=source_code,
                    ),
                    on_report_done=on_report_done,

                    use_streaming=use_streaming,
                ),
            ),
            (
                "source_reading",
                self._generate_report(
                    report_type="source_reading",
                    prompt=content_prefix + SOURCE_READING_PROMPT.format(
                        module_summaries=summaries_text,
                        key_files=self._build_key_files(gitnexus_data, deepwiki_data),
                        call_graph=self._build_call_graph(gitnexus_data, deepwiki_data),
                        source_code=source_code,
                    ),
                    on_report_done=on_report_done,

                    use_streaming=use_streaming,
                ),
            ),
            (
                "test_design",
                self._generate_report(
                    report_type="test_design",
                    prompt=content_prefix + TEST_DESIGN_PROMPT.format(
                        module_summaries=summaries_text,
                        business_flows=self._build_process_data(gitnexus_data, deepwiki_data),
                        api_interfaces=self._build_api_interfaces(gitnexus_data, deepwiki_data),
                    ),
                    on_report_done=on_report_done,

                    use_streaming=use_streaming,
                ),
            ),
        ]

        # Optional reports: only if requirements/design docs provided
        if requirements_doc:
            report_tasks.append((
                "requirements",
                self._generate_report(
                    report_type="requirements",
                    prompt=content_prefix + REQUIREMENTS_PROMPT.format(
                        requirements_doc=self._truncate(requirements_doc, 5000),
                        design_doc=self._truncate(design_doc or "（未提供设计文档）", 5000),
                        module_summaries=summaries_text,
                    ),
                    on_report_done=on_report_done,

                    use_streaming=use_streaming,
                ),
            ))

        if requirements_doc and design_doc:
            report_tasks.append((
                "traceability",
                self._generate_report(
                    report_type="traceability",
                    prompt=content_prefix + TRACEABILITY_PROMPT.format(
                        requirements_items=self._truncate(requirements_doc, 3000),
                        design_modules=self._truncate(design_doc, 3000),
                        module_summaries=summaries_text,
                        call_relations=self._build_call_graph(gitnexus_data, deepwiki_data),
                    ),
                    on_report_done=on_report_done,

                    use_streaming=use_streaming,
                ),
            ))

        sem = sem if sem is not None else asyncio.Semaphore(1)
        total = len(report_tasks)

        async def _guarded(idx: int, rtype: str, coro: Awaitable) -> None:
            async with sem:
                if on_report_start is not None:
                    await on_report_start(rtype, idx + 1, total)
                return await coro

        results = await asyncio.gather(
            *[_guarded(i, rtype, coro) for i, (rtype, coro) in enumerate(report_tasks)],
            return_exceptions=True,
        )

        for i, r in enumerate(results):
            if isinstance(r, BaseException):
                report_type = report_tasks[i][0]
                error_message = str(r)
                logger.error(
                    "Report generation failed in parallel: %s",
                    r,
                    extra={"task_id": self._task_id},
                )
                self._status_override = "completed_with_warnings"
                if on_report_failed is not None:
                    await on_report_failed(report_type, error_message)

        return self._generated_files

    async def _generate_report(
        self,
        report_type: str,
        prompt: str,
        on_report_done: Callable[[str, str, int], Awaitable[None]] | None = None,
        use_streaming: bool = False,
    ) -> None:
        """Generate a single report and save to disk."""
        filename = REPORT_FILE_MAP.get(report_type)
        if not filename:
            logger.warning("Unknown report type: %s", report_type)
            return

        try:
            messages = [{"role": "user", "content": prompt}]

            # Use streaming when requested AND the client has a real stream_complete
            # (not the base class fallback that just wraps complete()).
            has_real_streaming = (
                type(self._llm).stream_complete is not BaseLLMClient.stream_complete
            )

            if use_streaming and has_real_streaming:
                full_content = await self._llm.stream_complete_collected(
                    messages=messages,
                    max_tokens=min(MAX_OUTPUT_TOKENS, settings.llm_max_output_tokens),
                    temperature=0.3,
                )

                total_tokens = BaseLLMClient.estimate_tokens(full_content)
                # Use a placeholder model name since streaming doesn't return model info
                model_name = type(self._llm).__name__

                now = datetime.now(timezone.utc).isoformat()
                header = (
                    f"---\n"
                    f"report_type: {report_type}\n"
                    f"task_id: {self._task_id}\n"
                    f"generated_at: {now}\n"
                    f"model: {model_name}\n"
                    f"tokens: {total_tokens}\n"
                    f"---\n\n"
                )

                full_content = _validate_report_structure(full_content, report_type)

                filepath = self._output_dir / filename
                content = header + full_content
                await asyncio.to_thread(filepath.write_text, content, "utf-8")
                self._generated_files.append(filename)

                if on_report_done is not None:
                    await on_report_done(report_type, filename, total_tokens)

                logger.info(
                    "Report %s generated (streaming): %s (~%d tokens)",
                    report_type,
                    filename,
                    total_tokens,
                    extra={"task_id": self._task_id},
                )
            else:
                response: LLMResponse = await self._llm.complete(
                    messages=messages,
                    max_tokens=min(MAX_OUTPUT_TOKENS, settings.llm_max_output_tokens),
                    temperature=0.3,
                )

                # Prepend metadata header
                now = datetime.now(timezone.utc).isoformat()
                header = (
                    f"---\n"
                    f"report_type: {report_type}\n"
                    f"task_id: {self._task_id}\n"
                    f"generated_at: {now}\n"
                    f"model: {response.model}\n"
                    f"tokens: {response.usage.get('total_tokens', 0)}\n"
                    f"---\n\n"
                )

                validated_content = _validate_report_structure(response.content, report_type)

                filepath = self._output_dir / filename
                content = header + validated_content
                await asyncio.to_thread(filepath.write_text, content, "utf-8")
                self._generated_files.append(filename)

                total_tokens = response.usage.get("total_tokens", 0)
                if on_report_done is not None:
                    await on_report_done(report_type, filename, total_tokens)

                logger.info(
                    "Report %s generated: %s (%d tokens)",
                    report_type,
                    filename,
                    response.usage.get("total_tokens", 0),
                    extra={"task_id": self._task_id},
                )

        except Exception as exc:
            logger.exception("Report generation failed for %s: %s", report_type, exc, extra={"task_id": self._task_id})
            raise

    # ------------------------------------------------------------------
    # Context builders -- extract relevant data for each prompt
    # ------------------------------------------------------------------

    @staticmethod
    def _format_summaries(module_summaries: list[dict]) -> str:
        """Format module summaries for inclusion in report prompts."""
        parts: list[str] = []
        for ms in module_summaries:
            parts.append(f"### {ms['module_name']}\n{ms['summary']}")
        return "\n\n".join(parts) if parts else "（无模块摘要数据）"

    @staticmethod
    def _build_project_overview(gitnexus_data: dict, deepwiki_data: dict) -> str:
        """Build a brief project overview from available data."""
        parts: list[str] = []

        nodes = gitnexus_data.get("nodes", [])
        if nodes:
            file_count = sum(1 for n in nodes if n.get("label") == "File")
            func_count = sum(1 for n in nodes if n.get("label") == "Function")
            parts.append(f"代码图谱: {file_count} 个文件, {func_count} 个函数")

        doc = deepwiki_data.get("documentation", "")
        if doc:
            preview = doc[:500]
            parts.append(f"Wiki 概要: {preview}")

        return "\n".join(parts) if parts else "（无项目概览数据）"

    @staticmethod
    def _build_inter_module_deps(gitnexus_data: dict) -> str:
        """Extract cross-module dependency edges."""
        relationships = gitnexus_data.get("relationships", [])

        member_to_community: dict[str, str] = {}
        for edge in relationships:
            if edge.get("type") == "MEMBER_OF":
                member_to_community[edge["sourceId"]] = edge["targetId"]

        cross_deps: list[str] = []
        for edge in relationships:
            if edge.get("type") in ("CALLS", "IMPORTS", "DEPENDS_ON"):
                src_c = member_to_community.get(edge["sourceId"])
                tgt_c = member_to_community.get(edge["targetId"])
                if src_c and tgt_c and src_c != tgt_c:
                    cross_deps.append(f"{src_c} -> {tgt_c} ({edge.get('type')})")

        unique_deps = list(dict.fromkeys(cross_deps))
        return "\n".join(unique_deps[:50]) if unique_deps else "（无跨模块依赖数据）"

    @staticmethod
    def _extract_wiki_section(deepwiki_data: dict, keywords: list[str], max_chars: int = 2000) -> str:
        """Extract relevant sections from DeepWiki documentation by keyword matching."""
        doc = deepwiki_data.get("documentation", "")
        if not doc:
            return ""

        paragraphs = doc.split("\n\n")
        matched: list[str] = []
        for para in paragraphs:
            lower = para.lower()
            if any(kw.lower() in lower for kw in keywords):
                matched.append(para)

        combined = "\n\n".join(matched)
        if len(combined) > max_chars:
            combined = combined[:max_chars] + "\n...（已截断）"
        return combined

    @staticmethod
    def _build_process_data(gitnexus_data: dict, deepwiki_data: dict) -> str:
        """Extract process/flow data from GitNexus, supplemented by DeepWiki."""
        nodes = gitnexus_data.get("nodes", [])
        processes = [n for n in nodes if n.get("label") == "Process"]

        parts: list[str] = []
        if processes:
            for proc in processes[:10]:
                props = proc.get("properties", {})
                name = props.get("name", proc["id"])
                ptype = props.get("processType", "unknown")
                steps = props.get("stepCount", 0)
                parts.append(f"- {name} (类型: {ptype}, 步骤数: {steps})")
        else:
            wiki_section = ReportGenerator._extract_wiki_section(
                deepwiki_data,
                keywords=["flow", "process", "workflow", "流程", "步骤", "pipeline"],
            )
            if wiki_section:
                parts.append(f"[Wiki 流程信息]\n{wiki_section}")

        return "\n".join(parts) if parts else "（无流程数据）"

    @staticmethod
    def _build_cross_module_calls(gitnexus_data: dict, deepwiki_data: dict) -> str:
        """Extract cross-module call relationships, supplemented by DeepWiki."""
        relationships = gitnexus_data.get("relationships", [])

        member_to_community: dict[str, str] = {}
        for edge in relationships:
            if edge.get("type") == "MEMBER_OF":
                member_to_community[edge["sourceId"]] = edge["targetId"]

        cross_calls: list[str] = []
        for edge in relationships:
            if edge.get("type") == "CALLS":
                src_c = member_to_community.get(edge["sourceId"])
                tgt_c = member_to_community.get(edge["targetId"])
                if src_c and tgt_c and src_c != tgt_c:
                    cross_calls.append(
                        f"{edge['sourceId']} ({src_c}) -> {edge['targetId']} ({tgt_c})"
                    )

        parts = cross_calls[:50]

        wiki_section = ReportGenerator._extract_wiki_section(
            deepwiki_data,
            keywords=["module", "interaction", "integration", "模块", "集成", "交互"],
        )
        if wiki_section:
            parts.append(f"\n[Wiki 模块交互信息]\n{wiki_section}")

        return "\n".join(parts) if parts else "（无跨模块调用数据）"

    @staticmethod
    def _build_key_files(gitnexus_data: dict, deepwiki_data: dict) -> str:
        """Identify key files by edge count, enriched with DEFINES detail."""
        nodes = gitnexus_data.get("nodes", [])
        relationships = gitnexus_data.get("relationships", [])
        nodes_by_id = {n["id"]: n for n in nodes}

        edge_count: dict[str, int] = {}
        for edge in relationships:
            edge_count[edge["sourceId"]] = edge_count.get(edge["sourceId"], 0) + 1
            edge_count[edge["targetId"]] = edge_count.get(edge["targetId"], 0) + 1

        file_defines: dict[str, list[str]] = {}
        for edge in relationships:
            if edge.get("type") in ("DEFINES", "CONTAINS"):
                src = edge["sourceId"]
                tgt_node = nodes_by_id.get(edge["targetId"], {})
                tgt_label = tgt_node.get("label", "")
                tgt_name = tgt_node.get("properties", {}).get("name", edge["targetId"])
                if tgt_label in ("Function", "Class", "Struct"):
                    file_defines.setdefault(src, []).append(f"{tgt_label}:{tgt_name}")

        file_nodes = [n for n in nodes if n.get("label") in ("File", "Module")]
        ranked = sorted(
            file_nodes, key=lambda n: edge_count.get(n["id"], 0), reverse=True
        )

        parts: list[str] = []
        for node in ranked[:15]:
            props = node.get("properties", {})
            name = props.get("name", node["id"])
            count = edge_count.get(node["id"], 0)
            defines = file_defines.get(node["id"], [])
            detail = f", 定义: {', '.join(defines[:5])}" if defines else ""
            parts.append(f"- {name} (连接数: {count}{detail})")

        if len(file_nodes) < 5 and deepwiki_data.get("documentation"):
            parts.append("\n[注意: GitNexus 文件节点较少，DeepWiki 文档可供深入阅读参考]")

        return "\n".join(parts) if parts else "（无重点文件数据）"

    @staticmethod
    def _build_call_graph(gitnexus_data: dict, deepwiki_data: dict) -> str:
        """Format call graph edges as text, falling back to DEFINES when CALLS are absent."""
        relationships = gitnexus_data.get("relationships", [])
        call_edges = [
            e for e in relationships if e.get("type") in ("CALLS", "IMPORTS")
        ]

        parts: list[str] = []
        for edge in call_edges[:50]:
            parts.append(f"{edge['sourceId']} -> {edge['targetId']}")

        if not call_edges:
            nodes_by_id = {n["id"]: n for n in gitnexus_data.get("nodes", [])}
            define_edges = [
                e for e in relationships if e.get("type") in ("DEFINES", "CONTAINS")
            ]
            if define_edges:
                parts.append("[定义关系（CALLS 数据不可用，以定义关系代替）]")
                for edge in define_edges[:50]:
                    src_name = nodes_by_id.get(edge["sourceId"], {}).get("properties", {}).get("name", edge["sourceId"])
                    tgt_node = nodes_by_id.get(edge["targetId"], {})
                    tgt_name = tgt_node.get("properties", {}).get("name", edge["targetId"])
                    tgt_label = tgt_node.get("label", "")
                    parts.append(f"{src_name} -[{edge['type']}]-> {tgt_label}:{tgt_name}")

        if len(call_edges) < 5 and deepwiki_data.get("documentation"):
            parts.append("\n[注意: 调用图数据较少，DeepWiki 文档可供深入阅读参考]")

        return "\n".join(parts) if parts else "（无调用图数据）"

    @staticmethod
    def _build_api_interfaces(gitnexus_data: dict, deepwiki_data: dict) -> str:
        """Extract API endpoints from GitNexus, supplemented by DeepWiki API sections."""
        nodes = gitnexus_data.get("nodes", [])

        api_nodes: list[str] = []
        for node in nodes:
            props = node.get("properties", {})
            name = props.get("name", "")
            label = node.get("label", "")
            if label == "Function" and any(
                kw in name.lower()
                for kw in ("route", "endpoint", "handler", "api", "view")
            ):
                api_nodes.append(f"- {name} ({label})")

        parts = api_nodes[:20]

        wiki_section = ReportGenerator._extract_wiki_section(
            deepwiki_data,
            keywords=["api", "endpoint", "interface", "接口", "路由", "route"],
        )
        if wiki_section:
            parts.append(f"\n[Wiki API 信息]\n{wiki_section}")

        return (
            "\n".join(parts)
            if parts
            else "（无接口数据，请参考模块摘要中的对外接口部分）"
        )

    @staticmethod
    def _truncate(text: str, max_chars: int) -> str:
        """Truncate text to stay within token budget.

        When tiktoken is available, *max_chars* is treated as a **token** limit
        and the text is truncated at a token boundary.  Otherwise we fall back
        to approximating tokens as ``len(text) // 4`` and cutting by character
        count.
        """
        if _tiktoken_enc is not None:
            tokens = _tiktoken_enc.encode(text)
            if len(tokens) <= max_chars:
                return text
            truncated_tokens = tokens[:max_chars]
            result = _tiktoken_enc.decode(truncated_tokens)
            logger.info(
                "Truncated context: %d -> %d tokens",
                len(tokens),
                len(truncated_tokens),
            )
            return result + "\n...（已截断）"

        # Fallback: approximate tokens as chars / 4
        approx_tokens = len(text) // 4
        if approx_tokens <= max_chars:
            return text
        char_limit = max_chars * 4
        result = text[:char_limit]
        logger.info(
            "Truncated context (char approx): ~%d -> ~%d tokens",
            approx_tokens,
            max_chars,
        )
        return result + "\n...（已截断）"

    @staticmethod
    def _read_source_for_key_files(
        repo_path: str,
        gitnexus_data: dict,
        max_total_bytes: int = MAX_SOURCE_BYTES,
    ) -> str:
        """Read actual source files for key files identified by GitNexus edge count."""
        if not repo_path:
            return "（无源码路径）"

        repo = Path(repo_path)
        if not repo.is_dir():
            return "（源码路径不存在）"

        nodes = gitnexus_data.get("nodes", [])
        relationships = gitnexus_data.get("relationships", [])

        edge_count: dict[str, int] = {}
        for edge in relationships:
            edge_count[edge["sourceId"]] = edge_count.get(edge["sourceId"], 0) + 1
            edge_count[edge["targetId"]] = edge_count.get(edge["targetId"], 0) + 1

        file_nodes = [n for n in nodes if n.get("label") in ("File", "Module")]
        ranked = sorted(
            file_nodes, key=lambda n: edge_count.get(n["id"], 0), reverse=True
        )

        collected: list[str] = []
        total = 0

        for node in ranked[:15]:
            props = node.get("properties", {})
            name = props.get("name", node["id"])

            if Path(name).suffix not in _SOURCE_EXTS:
                continue

            candidate = repo / name
            if not candidate.is_file():
                continue

            try:
                size = candidate.stat().st_size
                if total + size > max_total_bytes:
                    continue
                content = candidate.read_text(encoding="utf-8", errors="replace")
                rel = candidate.relative_to(repo)
                ext = candidate.suffix.lstrip(".")
                collected.append(f"### {rel}\n```{ext}\n{content}\n```")
                total += size
            except OSError:
                continue

        if not collected:
            return "（未能读取源代码文件）"

        logger.info("Injected %d source files (%d bytes) into report prompt", len(collected), total)
        return "## 源代码内容（以下为实际文件内容，请据此分析）\n\n" + "\n\n".join(collected)


# ---------------------------------------------------------------------------
# Section blueprints for plan-driven report generation
# ---------------------------------------------------------------------------


_SECTION_BLUEPRINTS: dict[str, list[dict]] = {
    "project_structure": [
        {
            "heading": "项目目标与定位",
            "instructions": "用 3-5 句话描述项目主要目标、目标用户和典型使用场景；如证据不足直接写“数据不足，请验证”。",
            "min_chars": 80,
        },
        {
            "heading": "主要目录与入口",
            "instructions": "用 Markdown 表格列出主要目录、入口文件、配置/构建脚本；只允许出现证据卡中提到的路径。",
            "min_chars": 120,
        },
        {
            "heading": "本次分析对象与候选证据概览",
            "instructions": "回顾用户的分析对象，给出每个对象在证据卡中找到的关键文件和符号；未命中的对象必须标注 `待验证`。",
            "min_chars": 120,
        },
        {
            "heading": "下一步建议阅读的源文件",
            "instructions": "按优先级排序，给出 5-10 个文件，并解释为什么阅读它们对完成分析对象有帮助。",
            "min_chars": 100,
        },
    ],
    "module_map": [
        {
            "heading": "分组与责任",
            "instructions": "为每个分析单元写一段简短的“职责-范围-代表文件”三行说明。",
            "requires_mermaid": True,
            "min_chars": 150,
        },
        {
            "heading": "关键依赖与反向依赖",
            "instructions": "用 Markdown 表格列出每个单元的依赖与反向依赖；不要凭空捏造关系。",
            "min_chars": 120,
        },
        {
            "heading": "风险与待验证问题",
            "instructions": "列出当前证据无法回答的关键问题，每条均带 `待验证` 标签。",
            "min_chars": 100,
        },
    ],
    "source_reading": [
        {
            "heading": "重点文件阅读卡",
            "instructions": "为每个证据卡中包含 snippet 的文件输出：文件路径、所属单元、关键函数、关键状态变量、错误码、异常分支。",
            "min_chars": 200,
        },
        {
            "heading": "宏 / 函数指针 / 回调注意事项",
            "instructions": "若证据卡覆盖 C/C++ 代码，列出可能影响调用关系的宏、函数指针、回调和 switch-case 调度点。如不适用直接说明。",
            "min_chars": 80,
        },
        {
            "heading": "GitNexus 漏算的调用关系猜测",
            "instructions": "结合证据卡指出哪些调用关系可能被 GitNexus 漏算或误算，必须使用 `待验证` 前缀。",
            "min_chars": 80,
        },
    ],
    "business_flow": [
        {
            "heading": "核心业务流程清单",
            "instructions": "识别 3-5 个关键业务流程，给出目标、正常路径、关键状态、输入和输出。",
            "requires_mermaid": True,
            "min_chars": 200,
        },
        {
            "heading": "异常路径与异常传播",
            "instructions": "为每个流程列出异常路径、异常传播链、对外可观测的现象。",
            "min_chars": 150,
        },
        {
            "heading": "测试建议",
            "instructions": "为每个流程提出至少 2 条可执行测试建议（正向 + 异常）。",
            "min_chars": 120,
        },
    ],
    "gitnexus_reliability": [
        {
            "heading": "GitNexus 命中较准确的部分",
            "instructions": "总结 GitNexus 在本次分析中表现可靠的关系类型，例如 DEFINES / MEMBER_OF。",
            "min_chars": 80,
        },
        {
            "heading": "可能漏算或误算的部分",
            "instructions": "列出 GitNexus 在本仓库可能漏算的调用、宏、回调、switch-case；必要时给出可对照的源码线索。",
            "min_chars": 120,
        },
        {
            "heading": "推荐的验证工具",
            "instructions": "针对本仓库语言/构建配置推荐 clangd、cscope、ctags、rg、compile_commands.json 等验证手段。",
            "min_chars": 80,
        },
    ],
    "test_design": [
        {
            "heading": "测试视角的流程清单",
            "instructions": "对每个分析对象列出对应的可测试流程（黑盒视角）。",
            "min_chars": 120,
        },
        {
            "heading": "输入 / 状态 / 配置 / 环境因子",
            "instructions": "用表格列出影响每个流程的输入、状态、配置、环境因子。",
            "min_chars": 150,
        },
        {
            "heading": "可观测性与异常注入点",
            "instructions": "列出可用于验收的观测点（日志、返回码、计数器、告警）以及异常注入点。",
            "min_chars": 120,
        },
        {
            "heading": "SFMEA 草表",
            "instructions": "按以下列输出 SFMEA：功能/流程 | 故障模式 | 触发条件 | 异常注入点 | 异常传播路径 | 影响 | 可观测现象 | 严重度 | 发生概率 | 检测难度 | 建议测试。至少 5 行；证据不足处使用 `待验证`。",
            "requires_sfmea": True,
            "min_chars": 200,
        },
    ],
    "requirements_traceability": [
        {
            "heading": "需求 → 设计映射",
            "instructions": "用表格将需求材料中的条目映射到设计文档中的章节，未找到来源处标注 `待验证`。",
            "min_chars": 150,
        },
        {
            "heading": "设计 → 代码映射",
            "instructions": "用表格将设计章节映射到证据卡中的文件/符号。",
            "min_chars": 150,
        },
        {
            "heading": "缺口与风险",
            "instructions": "列出未覆盖的需求/设计条目以及推荐的验证动作。",
            "min_chars": 100,
        },
    ],
}


def _default_sections_for(spec: ReportSpec) -> list[dict]:
    """Build a minimal section blueprint for custom report specs."""
    instructions = (
        spec.audience or ""
    ) + "\n要求回答：\n" + "\n".join(f"- {q}" for q in (spec.questions or []))
    return [
        {
            "heading": "核心问题回答",
            "instructions": (instructions or "请基于证据卡回答该报告的核心问题。"),
            "min_chars": 120,
        },
        {
            "heading": "证据与待验证项",
            "instructions": "列出引用的关键证据，未找到答案的部分用 `待验证` 标注。",
            "min_chars": 80,
        },
    ]


# Stable mapping from template_id to output filename (Chinese-canonical
# names per §13.2; the legacy numeric files remain available through
# REPORT_FILE_MAP for old code paths).
_PLAN_REPORT_FILENAMES: dict[str, str] = {
    "project_structure": "10-项目结构初步理解.md",
    "module_map": "11-模块地图.md",
    "source_reading": "12-源码定向阅读记录.md",
    "business_flow": "13-关键业务流程分析.md",
    "gitnexus_reliability": "14-GitNexus结果可信度评估.md",
    "test_design": "15-测试视角代码理解.md",
    "requirements_traceability": "16-需求-设计-代码追踪.md",
}


def _plan_report_filename(spec: ReportSpec) -> str:
    if spec.template_id in _PLAN_REPORT_FILENAMES:
        return _PLAN_REPORT_FILENAMES[spec.template_id]
    # Custom reports get a slug-derived filename.
    slug = re.sub(r"[^\w一-鿿-]+", "_", spec.title).strip("_") or spec.id
    return f"99-{slug}.md"


_SFMEA_HEADER_RE = re.compile(
    r"\|\s*功能/?流程\s*\|.*故障模式.*\|.*触发条件.*\|", re.UNICODE,
)


def _section_is_invalid(body: str, *, min_chars: int, section: dict) -> bool:
    """Apply the §13.4 validity checks to a single section body."""
    if not body or len(body.strip()) < min_chars:
        return True
    text = body.strip()
    # Reject obvious truncation: dangling code fence / unmatched table row.
    if text.count("```") % 2 != 0:
        return True
    if section.get("requires_sfmea") and not _SFMEA_HEADER_RE.search(text):
        return True
    if section.get("requires_mermaid") and "```mermaid" not in text:
        return True
    return False
