"use client";

import React, { useMemo } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeRaw from "rehype-raw";
import type { PluggableList } from "unified";
import type { Components } from "react-markdown";
import { FileCode, ExternalLink } from "lucide-react";
import hljs from "highlight.js/lib/common";
import "highlight.js/styles/github.css";
import MermaidRenderer from "./MermaidRenderer";

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * Slugify a heading for use as an id attribute.
 * Keeps Unicode characters (Chinese, Japanese, etc.) intact so that
 * headings like "架构概述" produce a valid, non-empty id.
 */
function slugify(text: string): string {
  return text
    .trim()
    // spaces → hyphens
    .replace(/\s+/g, "-")
    // remove ASCII punctuation that shouldn't appear in an id
    .replace(/[!"#$%&'()*+,./:;<=>?@[\\\]^`{|}~]/g, "")
    // collapse consecutive hyphens
    .replace(/-+/g, "-")
    // strip leading/trailing hyphens
    .replace(/^-|-$/g, "")
    .toLowerCase();
}

function extractText(node: React.ReactNode): string {
  if (typeof node === "string") return node;
  if (typeof node === "number") return String(node);
  if (Array.isArray(node)) return node.map(extractText).join("");
  if (React.isValidElement(node)) {
    return extractText(
      (node.props as { children?: React.ReactNode }).children
    );
  }
  return "";
}

/**
 * Pattern for source citation links generated by wiki_prompts.py.
 * Format: `[filename.ext:start-end]()` or `[dir/file.ext]()`
 * Both produce href="" in markdown; the file path is in the link text.
 */
const FILE_CITATION_RE = /^([\w./\-]+\.\w+)(?::(\d+)-(\d+))?$/;
const NUMERIC_CITATION_RE = /^\[(\d+)\]$/;
type MarkdownVariant = "default" | "report";

export default function MarkdownRenderer({
  content,
  rehypePlugins = [],
  anchorBaseUrl,
  onCitationClick,
  enableNumericCitations = true,
  variant = "default",
}: {
  content: string;
  rehypePlugins?: PluggableList;
  /**
   * When set (embedded wiki view), `#anchor` links navigate to
   * `{anchorBaseUrl}#anchor` in a new tab — opening the standalone wiki page.
   * When absent (standalone wiki page), `#anchor` links scroll within the
   * current page.
   */
  anchorBaseUrl?: string;
  /**
   * When set, empty-href links whose text matches a file-path pattern are
   * treated as source citations and trigger this callback instead of
   * navigating.
   */
  onCitationClick?: (file: string, start?: number, end?: number) => void;
  /**
   * Numeric citations like [1] are used by InsightAskPanel footnotes, but wiki
   * pages should not route them into file preview APIs.
   */
  enableNumericCitations?: boolean;
  variant?: MarkdownVariant;
}) {
  const components: Components = useMemo(
    () => ({
      h1: ({ children }) => {
        const id = slugify(extractText(children)) || undefined;
        return (
          <h1
            id={id}
            className="font-display text-2xl font-bold text-on-surface mb-4 mt-6 scroll-mt-6"
          >
            {children}
          </h1>
        );
      },
      h2: ({ children }) => {
        const id = slugify(extractText(children)) || undefined;
        return (
          <h2
            id={id}
            className="font-display text-xl font-semibold text-on-surface mb-3 mt-5 scroll-mt-6 border-l-[3px] border-primary pl-3"
          >
            {children}
          </h2>
        );
      },
      h3: ({ children }) => {
        const id = slugify(extractText(children)) || undefined;
        return (
          <h3
            id={id}
            className="font-display text-lg font-medium text-on-surface mb-2 mt-4 scroll-mt-6 border-l-2 border-primary/40 pl-2.5"
          >
            {children}
          </h3>
        );
      },
      h4: ({ children }) => {
        const id = slugify(extractText(children)) || undefined;
        return (
          <h4
            id={id}
            className="font-display text-base font-medium text-on-surface/90 mb-1.5 mt-3 scroll-mt-6"
          >
            {children}
          </h4>
        );
      },
      p: ({ children }) => (
        <p className="text-on-surface/90 leading-relaxed mb-3">{children}</p>
      ),
      code: ({ className, children }) => {
        const isBlock = className?.startsWith("language-");
        if (className === "language-mermaid") {
          const chart = String(children).replace(/\n$/, "");
          return <MermaidRenderer chart={chart} />;
        }
        if (isBlock) {
          const lang = className?.replace("language-", "") ?? "";
          const raw = String(children).replace(/\n$/, "");
          let highlighted: string;
          try {
            highlighted =
              lang && hljs.getLanguage(lang)
                ? hljs.highlight(raw, { language: lang }).value
                : hljs.highlightAuto(raw).value;
          } catch {
            highlighted = escapeHtml(raw);
          }
          return (
            <div className="relative mb-4">
              {lang && (
                <span className="absolute top-0 right-0 text-[10px] font-mono text-on-surface-variant bg-surface-container-high px-2.5 py-1 rounded-bl-lg rounded-tr-lg border-b border-l border-outline-variant/40 select-none z-10">
                  {lang}
                </span>
              )}
              <pre className="bg-surface-container-lowest rounded-lg p-4 overflow-x-auto border border-outline-variant/40">
                <code
                  className="font-data text-xs hljs text-on-surface"
                  dangerouslySetInnerHTML={{ __html: highlighted }}
                />
              </pre>
            </div>
          );
        }
        return (
          <code className="font-data text-xs bg-primary-container px-1.5 py-0.5 rounded text-primary-fixed-dim border border-primary/10">
            {children}
          </code>
        );
      },
      ul: ({ children }) => (
        <ul className="pl-5 list-disc list-outside text-on-surface/90 mb-3 space-y-1.5 marker:text-primary/50">
          {children}
        </ul>
      ),
      ol: ({ children }) => (
        <ol className="pl-5 list-decimal list-outside text-on-surface/90 mb-3 space-y-1.5 marker:text-primary/60 marker:font-medium">
          {children}
        </ol>
      ),
      li: ({ children }) => (
        <li className="leading-relaxed">{children}</li>
      ),
      table: ({ children }) => (
        <div className="overflow-x-auto mb-4 rounded-lg border border-outline-variant/40 bg-surface-container-low">
          <table className="w-full text-sm border-collapse">{children}</table>
        </div>
      ),
      thead: ({ children }) => (
        <thead>{children}</thead>
      ),
      tbody: ({ children }) => (
        <tbody className="[&>tr:nth-child(even)]:bg-surface-container-high/20">{children}</tbody>
      ),
      tr: ({ children }) => (
        <tr className="border-b border-outline-variant/15 last:border-0 hover:bg-surface-container-high/30 transition-colors">
          {children}
        </tr>
      ),
      th: ({ children }) => (
        <th className="text-left text-xs font-semibold text-on-surface-variant/80 uppercase tracking-wide py-2.5 px-3 bg-surface-container-high border-b border-outline-variant/35">
          {children}
        </th>
      ),
      td: ({ children }) => (
        <td className="py-2 px-3 text-on-surface/80">{children}</td>
      ),
      blockquote: ({ children }) => (
        <blockquote className="bg-primary/5 border-l-4 border-primary/40 rounded-r-lg py-2.5 px-4 text-on-surface-variant mb-3">
          {children}
        </blockquote>
      ),
      details: ({ children }) => (
        <details className="mb-4 rounded-lg border border-outline-variant/25 bg-surface-container-low/50 p-3 open:bg-surface-container-low">
          {children}
        </details>
      ),
      summary: ({ children }) => (
        <summary className="cursor-pointer text-sm font-medium text-on-surface hover:text-primary">
          {children}
        </summary>
      ),
      a: ({ children, href }) => {
        const text = extractText(children);
        // Source citation: file-path references from wiki prompts, optionally numeric [1]
        const isFileCitationText = FILE_CITATION_RE.test(text);
        const isNumericCitationText = enableNumericCitations && NUMERIC_CITATION_RE.test(text);
        const isCitationHref =
          href &&
          (
            FILE_CITATION_RE.test(href) ||
            (enableNumericCitations && NUMERIC_CITATION_RE.test(href))
          );

        if (onCitationClick && (isFileCitationText || isNumericCitationText || (href && isCitationHref))) {
          const target = isCitationHref ? href! : text;
          
          // Case 1: Numeric Citation [1]
          const numMatch = enableNumericCitations ? NUMERIC_CITATION_RE.exec(target) : null;
          if (numMatch) {
            const citationIndex = numMatch[1];
            return (
              <button
                onClick={(e) => {
                  e.preventDefault();
                  onCitationClick(`citation-${citationIndex}`);
                }}
                className="inline-flex items-center justify-center min-w-[1.4em] h-[1.4em] text-[10px] font-bold text-primary bg-primary/10 border border-primary/20 rounded-sm hover:bg-primary/20 transition-all cursor-pointer mx-0.5 align-top shadow-sm"
                title={`查看引用来源 [${citationIndex}]`}
              >
                {citationIndex}
              </button>
            );
          }

          // Case 2: File Citation
          const m = FILE_CITATION_RE.exec(target);
          if (m) {
            const [, filePath, startStr, endStr] = m;
            const start = startStr ? parseInt(startStr, 10) : undefined;
            const end = endStr ? parseInt(endStr, 10) : undefined;
            return (
              <button
                onClick={(e) => {
                  e.preventDefault();
                  onCitationClick(filePath, start, end);
                }}
                className="inline-flex items-center gap-1.5 font-data text-[11px] text-secondary/90 hover:text-secondary bg-secondary/10 hover:bg-secondary/20 border border-secondary/30 px-2 py-0.5 rounded-md transition-all cursor-pointer leading-none my-0.5 align-middle shadow-sm hover:shadow-secondary/20 group"
                title={`查看源文件: ${filePath}${start ? `:${start}-${end}` : ""}`}
              >
                <FileCode size={11} className="opacity-60 group-hover:opacity-100 transition-opacity" />
                <span className="underline underline-offset-2 decoration-secondary/30 group-hover:decoration-secondary">
                  {children}
                </span>
              </button>
            );
          }
        }

        if (!enableNumericCitations && NUMERIC_CITATION_RE.test(text)) {
          return (
            <span
              className="inline-flex items-center justify-center min-w-[1.4em] h-[1.4em] text-[10px] font-bold text-primary/70 bg-primary/5 border border-primary/10 rounded-sm mx-0.5 align-top"
              title={`引用标记 ${text}`}
            >
              {text.replace(/\[|\]/g, "")}
            </span>
          );
        }

        if (href?.startsWith("#")) {
          if (anchorBaseUrl) {
            // Embedded view: open standalone wiki page at the target anchor.
            return (
              <a
                href={`${anchorBaseUrl}${href}`}
                className="text-primary underline underline-offset-2 hover:text-primary-fixed-dim inline-flex items-center gap-1 group"
                target="_blank"
                rel="noopener noreferrer"
              >
                {children}
                <ExternalLink size={10} className="opacity-0 group-hover:opacity-100 transition-opacity" />
              </a>
            );
          }
          // Standalone page: scroll within the current page.
          const targetId = href.slice(1);
          return (
            <a
              href={href}
              className="text-primary underline underline-offset-2 hover:text-primary-fixed-dim cursor-pointer"
              onClick={(e) => {
                e.preventDefault();
                document
                  .getElementById(targetId)
                  ?.scrollIntoView({ behavior: "smooth", block: "start" });
              }}
            >
              {children}
            </a>
          );
        }
        return (
          <a
            href={href}
            className="text-primary underline underline-offset-2 hover:text-primary-fixed-dim inline-flex items-center gap-1 group"
            target="_blank"
            rel="noopener noreferrer"
          >
            {children}
            <ExternalLink size={10} className="opacity-0 group-hover:opacity-100 transition-opacity" />
          </a>
        );
      },
    }),
    [anchorBaseUrl, enableNumericCitations, onCitationClick]
  );
  const appliedRehypePlugins = useMemo<PluggableList>(
    () => [rehypeRaw, ...rehypePlugins],
    [rehypePlugins]
  );
  const renderedContent = useMemo(
    () => content.replaceAll("<redacted>", "&lt;redacted&gt;"),
    [content],
  );

  return (
    <div
      className={`prose-kinetic max-w-full overflow-hidden break-words ${
        variant === "report" ? "prose-report" : ""
      }`}
    >
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        rehypePlugins={appliedRehypePlugins}
        components={components}
      >
        {renderedContent}
      </ReactMarkdown>
    </div>
  );
}
