"""CGC (CodeGraphContext) launcher utilities for the native deployer.

CGC runs as a separate HTTP daemon started via ``python -m codegraphcontext api start``.
We use the module entrypoint rather than the ``cgc`` script shim because Windows
entry-point shims (.exe wrappers generated by pip) can silently fail after a Python
upgrade or venv relocation, whereas ``python -m <pkg>`` always uses the venv's own
interpreter and is immune to stale shim paths.

This module provides path resolution and working-directory helpers used by
deployers/native.py to launch and manage the CGC process.
"""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

# D:\coworkers\ (parent of the codetalk repo)
# cgc_launcher.py lives at deployer/cgc_launcher.py → 3 levels up = D:\coworkers\
_COWORKERS: Path = Path(__file__).parent.parent.parent

CGC_DEFAULT_VENV: Path = _COWORKERS / "cgc-venv"
CGC_DEFAULT_PORT: int = 7072


def resolve_cgc_cmd(config: dict | None = None) -> list[str] | None:
    """Return the command list to start CGC, or None if no usable venv is found.

    Returns ``[python_exe, "-m", "codegraphcontext"]`` for the first venv whose
    Python interpreter exists.  Callers append ``["api", "start", ...]`` as needed.

    Prefers ``python -m codegraphcontext`` over the ``cgc`` script shim because
    Windows entry-point shims can silently fail after Python upgrades or venv
    relocations, while ``python -m <pkg>`` always routes through the venv's own
    interpreter.

    Priority:
      1. config['cgc_venv_path'] when set and non-empty
      2. CGC_DEFAULT_VENV  (D:\\coworkers\\cgc-venv)
      3. D:\\coworkers\\cgc-venv-throwaway  (legacy pre-rename name)
    """
    candidates: list[Path] = []
    if config:
        venv_path = str(config.get("cgc_venv_path", "")).strip()
        if venv_path:
            candidates.append(Path(venv_path))
    candidates.append(CGC_DEFAULT_VENV)
    candidates.append(_COWORKERS / "cgc-venv-throwaway")

    scripts = "Scripts" if sys.platform == "win32" else "bin"
    python_name = "python.exe" if sys.platform == "win32" else "python"

    for venv in candidates:
        python_exe = venv / scripts / python_name
        if python_exe.exists():
            return [str(python_exe), "-m", "codegraphcontext"]
    return None


class CGCInstallError(RuntimeError):
    """CGC or its dependencies could not be installed."""


def ensure_cgc_installed(venv_path: Path | None = None) -> None:
    """Ensure the CGC venv exists with codegraphcontext + mcp installed.

    Idempotent: returns immediately if cgc.exe already exists in the venv.
    Otherwise creates the venv (if absent) and runs pip install for both
    ``codegraphcontext`` and ``mcp`` (which cgc 0.x omits from its own deps).

    Args:
        venv_path: Target venv directory. Defaults to CGC_DEFAULT_VENV.

    Raises:
        CGCInstallError: on venv creation failure or pip install failure.
    """
    venv: Path = venv_path if isinstance(venv_path, Path) else (
        Path(venv_path) if venv_path else CGC_DEFAULT_VENV
    )
    scripts = "Scripts" if sys.platform == "win32" else "bin"
    exe_name = "cgc.exe" if sys.platform == "win32" else "cgc"
    python_exe = venv / scripts / ("python.exe" if sys.platform == "win32" else "python")

    # Use `python -m pip` rather than `pip.exe` — the pip script wrapper can be
    # broken/missing (e.g. after a pip upgrade that replaces the launcher) while
    # the underlying module and Python executable remain fully functional.
    def _pip(*args: str) -> list:
        return [str(python_exe), "-m", "pip", *args]

    def _pip_healthy() -> bool:
        """Return True only if this venv's Python can actually run pip.

        Checks file existence first to avoid spawning a process for a missing
        interpreter (e.g. pyvenv.cfg pointing to a deleted Python install).
        """
        if not python_exe.exists():
            return False
        try:
            r = subprocess.run(_pip("--version"), capture_output=True)
            return r.returncode == 0
        except (FileNotFoundError, OSError):
            return False

    # Cache once — used in both the early-exit guard and the recreate guard.
    _pip_ok = _pip_healthy()

    if (venv / scripts / exe_name).exists() and _pip_ok:
        # cgc.exe present + interpreter healthy.
        # Also verify the module entrypoint itself works — the pip shim can be
        # stale even when pip is healthy (e.g. after python upgrade or venv move).
        mod_check = subprocess.run(
            [str(python_exe), "-m", "codegraphcontext", "--version"],
            capture_output=True,
        )
        if mod_check.returncode == 0:
            # Module entrypoint OK — verify mcp is also installed
            chk = subprocess.run(_pip("show", "mcp"), capture_output=True)
            if chk.returncode == 0:
                return  # fully installed
            # mcp missing — install it without reinstalling codegraphcontext
            result = subprocess.run(_pip("install", "mcp"), capture_output=True, text=True)
            if result.returncode != 0:
                detail = (result.stderr or result.stdout or "unknown error").strip()
                raise CGCInstallError(
                    f"CGC 依赖安装失败 (mcp): {detail}\n"
                    f"请手动运行: {python_exe} -m pip install mcp"
                )
            return
        # Module check failed — fall through to full reinstall below

    # cgc.exe absent OR interpreter broken — (re)create venv and install all deps
    if not python_exe.exists() or not _pip_ok:
        result = subprocess.run(
            [sys.executable, "-m", "venv", str(venv)],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            detail = (result.stderr or result.stdout or "unknown error").strip()
            raise CGCInstallError(
                f"CGC 虚拟环境创建失败 ({venv}): {detail}\n"
                f"请手动运行: python -m venv {venv}"
            )

    for pkg in ("codegraphcontext", "mcp"):
        result = subprocess.run(
            _pip("install", pkg),
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            detail = (result.stderr or result.stdout or "unknown error").strip()
            raise CGCInstallError(
                f"CGC 依赖安装失败 ({pkg}): {detail}\n"
                f"请手动运行: {python_exe} -m pip install {pkg}"
            )


def cgc_cwd() -> str:
    """Return the working directory for the cgc process.

    We use ~/.codegraphcontext/ rather than the codetalk project directory
    to avoid a GBK codec error: when cgc's cwd contains a .env file with
    non-ASCII characters (e.g. Chinese comments), cgc's own .env loading
    fails on Windows because the system locale defaults to GBK.
    """
    cwd = Path(os.path.expanduser("~")) / ".codegraphcontext"
    cwd.mkdir(parents=True, exist_ok=True)
    return str(cwd)
