"""Workflow header/version lifecycle routes for Workbench V2."""

from __future__ import annotations

import json
import sqlite3
import uuid
from copy import deepcopy
from dataclasses import asdict
from pathlib import Path
from typing import Any

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field, StrictInt

from app.config import settings
from app.services.agent_runtimes import list_agent_runtimes_sync
from app.services.evidence_memory import EvidenceMemoryStore
from app.services.external_agent_discovery import external_agent_provider_specs
from app.services.test_semantic_library import TestSemanticLibraryStore
from app.services.workbench_task_run import WorkbenchTaskRunPreparer, refresh_run_snapshot_v3
from app.services.workflow_graph import (
    WorkflowGraphValidationError,
    compile_workflow_graph,
    validate_workflow_graph,
)
from app.services.workflow_handler_registry import workflow_handler_capability_snapshot
from app.services.workflow_presets import reserved_builtin_workflow_ids
from app.services.workflow_dsl import WorkflowStore
from app.services.workflow_version_store import (
    ExpectedWorkflowDraftRevisionError,
    PublishedWorkflowVersionError,
    StaleWorkflowDraftError,
    WorkflowDraftExistsError,
    WorkflowVersionError,
    WorkflowVersionStore,
    legacy_definition_to_v2_graph,
)
from app.services.workflow_authoring_factory import (
    CANVAS_TEMPLATES,
    TECHNICAL_ID_FIELDS,
    CanvasAuthoringError,
    build_canvas_graph,
    backend_commit_sha,
    build_v3_edge,
    build_v3_node,
    build_v3_port,
    migrate_legacy_graph_to_v3,
    new_workflow_id,
)
from app.services.workflow_node_registry import executable_node_definition


router = APIRouter(prefix="/api/workbench", tags=["workbench-v2-workflows"])
_BUILTIN_WORKFLOW_IDS = reserved_builtin_workflow_ids()


class WorkflowHeaderUpdateRequest(BaseModel):
    name: str | None = None
    description: str | None = None


class WorkflowDraftCreateRequest(BaseModel):
    based_on_version_id: str | None = None


class WorkflowDraftUpdateRequest(BaseModel):
    authoring_graph: dict[str, Any]
    expected_revision: int | None = Field(default=None, ge=1)


class WorkflowPublishRequest(BaseModel):
    expected_revision: StrictInt | None = None


class WorkflowDerivedRequest(BaseModel):
    expected_revision: StrictInt | None = None


class WorkflowTrialRunRequest(BaseModel):
    workspace_id: str = Field(min_length=1)
    inputs: dict[str, Any] = Field(default_factory=dict)
    node_id: str | None = None
    expected_revision: StrictInt | None = None


def _canvas_error(code: str, message: str, *, status_code: int = 422) -> HTTPException:
    return HTTPException(status_code=status_code, detail={"code": code, "message": message})


def _reject_client_owned_identity_fields(payload: dict[str, Any]) -> None:
    forbidden = sorted((TECHNICAL_ID_FIELDS | {"id"}) & set(payload))
    if forbidden:
        raise _canvas_error(
            "client_technical_ids_forbidden",
            f"Technical IDs are generated by the server: {', '.join(forbidden)}",
        )


def _expected_v3_revision(payload: dict[str, Any]) -> int:
    value = payload.get("expected_revision")
    if isinstance(value, bool) or not isinstance(value, int) or value < 1:
        raise _canvas_error(
            "expected_revision_required",
            "画布已更新，请先刷新获取最新版本后再操作。",
        )
    return value


def _persist_v3_canvas_command(
    version_id: str, *, expected_revision: int, authoring_graph: dict[str, Any]
):
    try:
        return workflow_version_store().update_v3_draft_from_server_command(
            version_id,
            expected_revision=expected_revision,
            authoring_graph=authoring_graph,
        )
    except StaleWorkflowDraftError as exc:
        raise _canvas_error("stale_draft", str(exc), status_code=409) from exc
    except ExpectedWorkflowDraftRevisionError as exc:
        raise _canvas_error("expected_revision_required", str(exc)) from exc
    except WorkflowVersionError as exc:
        raise _canvas_error("canvas_command_invalid", str(exc)) from exc


def _workflow_version_payload(version: Any) -> dict[str, Any]:
    """Expose V3 CAS state without changing frozen V1/V2 version JSON."""
    payload = asdict(version)
    if version.draft_revision is not None:
        payload["draft_revision"] = version.draft_revision
    return payload


def _update_compiled_draft(
    version: Any, *, expected_revision: int | None = None, **changes: Any
):
    """Persist derived validation/plan state under the same V3 CAS contract."""
    try:
        return workflow_version_store().update_draft(
            version.version_id,
            authoring_graph=version.authoring_graph,
            expected_revision=(
                expected_revision
                if version.authoring_graph.get("schema_version") == 3
                else None
            ),
            **changes,
        )
    except StaleWorkflowDraftError as exc:
        raise _canvas_error("stale_draft", str(exc), status_code=409) from exc
    except ExpectedWorkflowDraftRevisionError as exc:
        raise _canvas_error("expected_revision_required", str(exc)) from exc


def _with_draft_revision(payload: dict[str, Any], version: Any) -> dict[str, Any]:
    response = deepcopy(payload)
    if version.draft_revision is not None:
        response["draft_revision"] = version.draft_revision
    return response


def _require_current_v3_revision(version: Any, expected_revision: int) -> None:
    """Fail stale commands before validating a graph snapshot they no longer own."""
    if version.draft_revision != expected_revision:
        raise _canvas_error(
            "stale_draft",
            "画布已被其他窗口更新。请刷新后确认最新内容，再重新操作。",
            status_code=409,
        )


def _derived_expected_revision(version: Any, value: int | None) -> int | None:
    if version.authoring_graph.get("schema_version") != 3:
        return None
    expected_revision = _expected_v3_revision({"expected_revision": value})
    _require_current_v3_revision(version, expected_revision)
    return expected_revision


def workflow_version_store() -> WorkflowVersionStore:
    return WorkflowVersionStore(settings.data_path / "workbench" / "workflows.db")


def _require_v2() -> None:
    # Kept as a compatibility seam for callers of the versioned API. The
    # versioned Workbench is now the only runtime and cannot be disabled.
    return None


def _require_mutable_workflow(workflow_id: str) -> None:
    if workflow_id in _BUILTIN_WORKFLOW_IDS:
        raise HTTPException(status_code=409, detail="内置工作流是只读的，请另存为自定义工作流")


@router.post("/workflows/new", status_code=201)
async def create_canvas_workflow(payload: dict[str, Any]) -> dict[str, Any]:
    """Create a Canvas First V3 draft without accepting client technical IDs."""
    _require_v2()
    _reject_client_owned_identity_fields(payload)
    unknown = sorted(set(payload) - {"template", "name", "description"})
    if unknown:
        raise _canvas_error("canvas_create_fields_invalid", f"Unsupported create fields: {', '.join(unknown)}")
    template = str(payload.get("template") or "").strip()
    if template not in CANVAS_TEMPLATES:
        raise _canvas_error("canvas_template_invalid", "template must be blank or free_source_analysis")
    name = str(payload.get("name") or "").strip()
    if not name:
        raise _canvas_error("workflow_name_required", "name is required")
    workflow_id = new_workflow_id()
    graph = build_canvas_graph(
        workflow_id=workflow_id,
        name=name,
        description=str(payload.get("description") or ""),
        template=template,
    )
    try:
        header, draft = workflow_version_store().create_canvas_workflow(
            workflow_id=workflow_id,
            name=name,
            description=str(payload.get("description") or ""),
            authoring_graph=graph,
        )
    except WorkflowVersionError as exc:
        raise _canvas_error("canvas_create_failed", str(exc)) from exc
    return {
        "workflow": asdict(header),
        "draft": _workflow_version_payload(draft),
        "designer_url": f"/workflows/{header.workflow_id}/designer",
        "meta": {"backend_commit_sha": _backend_commit_sha(), "schema_version": 3},
    }


@router.patch("/workflows/{workflow_id}")
async def update_workflow_header(
    workflow_id: str, payload: WorkflowHeaderUpdateRequest
) -> dict[str, Any]:
    _require_v2()
    _require_mutable_workflow(workflow_id)
    try:
        header = workflow_version_store().update_workflow(
            workflow_id,
            name=payload.name,
            description=payload.description,
        )
    except KeyError:
        raise HTTPException(status_code=404, detail=f"Unknown workflow: {workflow_id}")
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    return asdict(header)


@router.post("/workflows/{workflow_id}/archive")
async def archive_workflow_header(workflow_id: str) -> dict[str, Any]:
    _require_v2()
    _require_mutable_workflow(workflow_id)
    try:
        return asdict(workflow_version_store().archive_workflow(workflow_id))
    except KeyError:
        raise HTTPException(status_code=404, detail=f"Unknown workflow: {workflow_id}")


@router.get("/workflows/{workflow_id}/versions")
async def list_workflow_versions(workflow_id: str) -> dict[str, Any]:
    _require_v2()
    try:
        items = workflow_version_store().list_versions(workflow_id)
    except KeyError:
        raise HTTPException(status_code=404, detail=f"Unknown workflow: {workflow_id}")
    return {"items": [_workflow_version_payload(item) for item in items]}


@router.post("/workflows/{workflow_id}/versions", status_code=201)
async def create_workflow_draft(
    workflow_id: str, payload: WorkflowDraftCreateRequest
) -> dict[str, Any]:
    _require_v2()
    _require_mutable_workflow(workflow_id)
    try:
        version = workflow_version_store().create_draft(
            workflow_id,
            based_on_version_id=payload.based_on_version_id,
        )
    except KeyError:
        raise HTTPException(status_code=404, detail=f"Unknown workflow: {workflow_id}")
    except WorkflowDraftExistsError as exc:
        raise HTTPException(status_code=409, detail=str(exc))
    except WorkflowVersionError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    return _workflow_version_payload(version)


@router.post("/workflows/{workflow_id}/copy", status_code=201)
async def copy_workflow_as_custom_draft(workflow_id: str) -> dict[str, Any]:
    """Copy a read-only template into a distinct editable V2 draft."""
    _require_v2()
    store = workflow_version_store()
    try:
        source = store.get_workflow(workflow_id)
    except KeyError:
        raise HTTPException(status_code=404, detail=f"Unknown workflow: {workflow_id}")
    custom_id = f"{source.workflow_id[:110]}_custom_{uuid.uuid4().hex[:8]}"
    try:
        _header, draft = store.copy_workflow_as_custom_draft(
            source.workflow_id,
            workflow_id=custom_id,
            name=f"{source.name}（副本）",
            description=source.description,
        )
    except WorkflowVersionError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    return asdict(draft)


@router.get("/workflows/{workflow_id}/versions/{version_id}")
async def get_workflow_version(workflow_id: str, version_id: str) -> dict[str, Any]:
    _require_v2()
    version = _version_for_workflow(workflow_id, version_id)
    response = _workflow_version_payload(version)
    schema_version = version.authoring_graph.get("schema_version")
    if schema_version == 1:
        response["editor_mode"] = "read_only_legacy"
    elif schema_version == 2:
        response["editor_mode"] = "legacy"
    else:
        response["editor_mode"] = "canvas"
    return response


@router.put("/workflows/{workflow_id}/versions/{version_id}")
async def update_workflow_draft(
    workflow_id: str,
    version_id: str,
    payload: WorkflowDraftUpdateRequest,
) -> dict[str, Any]:
    _require_v2()
    _require_mutable_workflow(workflow_id)
    _version_for_workflow(workflow_id, version_id)
    try:
        version = workflow_version_store().update_draft(
            version_id,
            authoring_graph=payload.authoring_graph,
            expected_revision=payload.expected_revision,
        )
    except StaleWorkflowDraftError as exc:
        raise _canvas_error("stale_draft", str(exc), status_code=409) from exc
    except ExpectedWorkflowDraftRevisionError as exc:
        raise _canvas_error("expected_revision_required", str(exc)) from exc
    except PublishedWorkflowVersionError as exc:
        raise HTTPException(status_code=409, detail=str(exc))
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    return _workflow_version_payload(version)


@router.post("/workflows/{workflow_id}/versions/{version_id}/nodes", status_code=201)
async def add_canvas_node(
    workflow_id: str, version_id: str, payload: dict[str, Any]
) -> dict[str, Any]:
    """Add one Phase 3 node and allocate every node-owned identifier server-side."""
    _require_v2()
    _require_mutable_workflow(workflow_id)
    version = _require_v3_mutable_draft(workflow_id, version_id)
    expected_revision = _expected_v3_revision(payload)
    _require_current_v3_revision(version, expected_revision)
    _reject_client_owned_identity_fields(payload)
    unknown = sorted(
        set(payload) - {"expected_revision", "kind", "label", "position", "config"}
    )
    if unknown:
        raise _canvas_error(
            "node_command_fields_invalid",
            f"Unsupported node fields: {', '.join(unknown)}",
        )
    kind = str(payload.get("kind") or "").strip()
    if executable_node_definition(kind) is None:
        raise _canvas_error("node_kind_not_executable", f"Node kind is unavailable: {kind}")
    config = payload.get("config") if isinstance(payload.get("config"), dict) else {}
    try:
        node = build_v3_node(
            kind,
            label=str(payload.get("label") or "").strip() or None,
            position=payload.get("position") if isinstance(payload.get("position"), dict) else None,
            config=config,
        )
    except (CanvasAuthoringError, ValueError) as exc:
        raise _canvas_error("client_technical_ids_forbidden" if "technical_ids" in str(exc) else "node_command_invalid", str(exc)) from exc
    graph = deepcopy(version.authoring_graph)
    graph["nodes"].append(node)
    draft = _persist_v3_canvas_command(
        version_id, expected_revision=expected_revision, authoring_graph=graph
    )
    return {"node": node, "draft": _workflow_version_payload(draft)}


@router.post("/workflows/{workflow_id}/versions/{version_id}/nodes/{node_id}/ports", status_code=201)
async def add_canvas_port(
    workflow_id: str, version_id: str, node_id: str, payload: dict[str, Any]
) -> dict[str, Any]:
    """Add a typed V3 port without allowing a client-selected port ID."""
    _require_v2()
    _require_mutable_workflow(workflow_id)
    version = _require_v3_mutable_draft(workflow_id, version_id)
    expected_revision = _expected_v3_revision(payload)
    _require_current_v3_revision(version, expected_revision)
    _reject_client_owned_identity_fields(payload)
    direction = str(payload.get("direction") or "").strip()
    if direction not in {"inputs", "outputs"}:
        raise _canvas_error("port_direction_invalid", "direction must be inputs or outputs")
    port_type = str(payload.get("type") or "").strip()
    if not port_type:
        raise _canvas_error("port_type_required", "type is required")
    graph = deepcopy(version.authoring_graph)
    node = next((item for item in graph.get("nodes") or [] if str(item.get("id") or "") == node_id), None)
    if not isinstance(node, dict):
        raise HTTPException(status_code=404, detail=f"Unknown workflow node: {node_id}")
    port = build_v3_port(
        label=str(payload.get("label") or port_type),
        port_type=port_type,
        required=bool(payload.get("required", False)),
        collection=bool(payload.get("collection", False)),
    )
    node.setdefault("ports", {}).setdefault(direction, []).append(port)
    draft = _persist_v3_canvas_command(
        version_id, expected_revision=expected_revision, authoring_graph=graph
    )
    return {"port": port, "draft": _workflow_version_payload(draft)}


@router.patch(
    "/workflows/{workflow_id}/versions/{version_id}/nodes/{node_id}/ports/{port_id}"
)
async def update_canvas_port(
    workflow_id: str,
    version_id: str,
    node_id: str,
    port_id: str,
    payload: dict[str, Any],
) -> dict[str, Any]:
    """Edit user-facing port properties without replacing its stable ID."""
    _require_v2()
    _require_mutable_workflow(workflow_id)
    version = _require_v3_mutable_draft(workflow_id, version_id)
    expected_revision = _expected_v3_revision(payload)
    _require_current_v3_revision(version, expected_revision)
    _reject_client_owned_identity_fields(payload)
    unknown = sorted(
        set(payload) - {"expected_revision", "label", "type", "required", "collection"}
    )
    if unknown:
        raise _canvas_error("port_update_fields_invalid", f"Unsupported port fields: {', '.join(unknown)}")
    graph = deepcopy(version.authoring_graph)
    port = _find_canvas_port(graph, node_id, port_id)
    if "label" in payload:
        label = str(payload["label"] or "").strip()
        if not label:
            raise _canvas_error("port_label_required", "Port label is required")
        port["label"] = label
    if "type" in payload:
        port_type = str(payload["type"] or "").strip()
        if not port_type:
            raise _canvas_error("port_type_required", "Port type is required")
        port["type"] = port_type
    if "required" in payload:
        port["required"] = bool(payload["required"])
    if "collection" in payload:
        port["collection"] = bool(payload["collection"])
    for edge in graph.get("edges") or []:
        if isinstance(edge, dict) and edge.get("kind", "data") == "data":
            _assert_edge_ports_exist(
                graph,
                edge.get("source") or {},
                edge.get("target") or {},
                exclude_edge_id=str(edge.get("id") or ""),
            )
    draft = _persist_v3_canvas_command(
        version_id, expected_revision=expected_revision, authoring_graph=graph
    )
    return {"port": port, "draft": _workflow_version_payload(draft)}


@router.delete(
    "/workflows/{workflow_id}/versions/{version_id}/nodes/{node_id}/ports/{port_id}"
)
async def delete_canvas_port(
    workflow_id: str, version_id: str, node_id: str, port_id: str, payload: dict[str, Any]
) -> dict[str, Any]:
    """Delete a V3 port and every edge that referenced it atomically."""
    _require_v2()
    _require_mutable_workflow(workflow_id)
    version = _require_v3_mutable_draft(workflow_id, version_id)
    expected_revision = _expected_v3_revision(payload)
    _require_current_v3_revision(version, expected_revision)
    _reject_client_owned_identity_fields(payload)
    graph = deepcopy(version.authoring_graph)
    node = next(
        (item for item in graph.get("nodes") or [] if isinstance(item, dict) and str(item.get("id") or "") == node_id),
        None,
    )
    if node is None:
        raise HTTPException(status_code=404, detail=f"Unknown workflow node: {node_id}")
    found = False
    ports = node.get("ports") if isinstance(node.get("ports"), dict) else {}
    for direction in ("inputs", "outputs"):
        current = ports.get(direction) if isinstance(ports.get(direction), list) else []
        next_ports = [port for port in current if str(port.get("id") or "") != port_id]
        found = found or len(next_ports) != len(current)
        ports[direction] = next_ports
    if not found:
        raise HTTPException(status_code=404, detail=f"Unknown workflow port: {port_id}")
    graph["edges"] = [
        edge
        for edge in graph.get("edges") or []
        if str((edge.get("source") or {}).get("port_id") or "") != port_id
        and str((edge.get("target") or {}).get("port_id") or "") != port_id
    ]
    draft = _persist_v3_canvas_command(
        version_id, expected_revision=expected_revision, authoring_graph=graph
    )
    return {"draft": _workflow_version_payload(draft)}


@router.post("/workflows/{workflow_id}/versions/{version_id}/edges", status_code=201)
async def add_canvas_edge(
    workflow_id: str, version_id: str, payload: dict[str, Any]
) -> dict[str, Any]:
    """Create a data edge with a server-generated identity."""
    _require_v2()
    _require_mutable_workflow(workflow_id)
    version = _require_v3_mutable_draft(workflow_id, version_id)
    expected_revision = _expected_v3_revision(payload)
    _require_current_v3_revision(version, expected_revision)
    _reject_client_owned_identity_fields(payload)
    source = payload.get("source") if isinstance(payload.get("source"), dict) else {}
    target = payload.get("target") if isinstance(payload.get("target"), dict) else {}
    graph = deepcopy(version.authoring_graph)
    _assert_edge_ports_exist(graph, source, target)
    edge = build_v3_edge(
        source_node_id=str(source.get("node_id") or ""),
        source_port_id=str(source.get("port_id") or ""),
        target_node_id=str(target.get("node_id") or ""),
        target_port_id=str(target.get("port_id") or ""),
    )
    graph["edges"].append(edge)
    draft = _persist_v3_canvas_command(
        version_id, expected_revision=expected_revision, authoring_graph=graph
    )
    return {"edge": edge, "draft": _workflow_version_payload(draft)}


@router.post("/workflows/{workflow_id}/versions/{version_id}/copy-to-v3", status_code=201)
async def copy_workflow_version_to_v3(workflow_id: str, version_id: str) -> dict[str, Any]:
    """Explicitly copy a legacy version into a separate Canvas First V3 draft."""
    _require_v2()
    source = _version_for_workflow(workflow_id, version_id)
    source_header = workflow_version_store().get_workflow(workflow_id)
    source_schema_version = source.authoring_graph.get("schema_version")
    if source_schema_version not in {1, 2}:
        raise _canvas_error(
            "copy_to_v3_source_schema_invalid",
            "Only legacy V1 or V2 workflow versions can be copied to V3.",
            status_code=409,
        )
    target_workflow_id = new_workflow_id()
    target_name = f"{source_header.name} copy"
    source_graph = source.authoring_graph
    if source_schema_version == 1:
        definition = source.compiled_definition or source_graph.get("legacy_definition")
        if not isinstance(definition, dict):
            raise _canvas_error(
                "legacy_definition_missing",
                "The legacy workflow has no definition to copy.",
            )
        source_graph = legacy_definition_to_v2_graph(definition, source_header)
    graph = migrate_legacy_graph_to_v3(
        source_graph,
        workflow_id=target_workflow_id,
        name=target_name,
        description=source_header.description,
    )
    header, draft = workflow_version_store().create_canvas_workflow(
        workflow_id=target_workflow_id,
        name=target_name,
        description=source_header.description,
        authoring_graph=graph,
    )
    return {
        "source_workflow_id": workflow_id,
        "source_version_id": version_id,
        "workflow": asdict(header),
        "draft": _workflow_version_payload(draft),
        "designer_url": f"/workflows/{header.workflow_id}/designer",
        "migration_preview": {
            "source_schema_version": source.authoring_graph.get("schema_version"),
            "target_schema_version": 3,
            "source_preserved": True,
        },
    }


@router.post("/workflows/{workflow_id}/versions/{version_id}/validate")
async def validate_workflow_version(
    workflow_id: str,
    version_id: str,
    payload: WorkflowDerivedRequest | None = None,
) -> dict[str, Any]:
    _require_v2()
    _require_mutable_workflow(workflow_id)
    version = _version_for_workflow(workflow_id, version_id)
    if version.state != "draft":
        raise HTTPException(status_code=409, detail="Published workflow versions are immutable")
    expected_revision = _derived_expected_revision(
        version, payload.expected_revision if payload else None
    )
    validation = validate_workflow_graph(
        version.authoring_graph,
        capabilities=_workflow_graph_capabilities(),
    )
    saved = _update_compiled_draft(
        version, expected_revision=expected_revision, validation=validation
    )
    return _with_draft_revision(validation, saved)


@router.post("/workflows/{workflow_id}/versions/{version_id}/compile")
async def compile_workflow_version(
    workflow_id: str,
    version_id: str,
    payload: WorkflowDerivedRequest | None = None,
) -> dict[str, Any]:
    _require_v2()
    _require_mutable_workflow(workflow_id)
    version = _version_for_workflow(workflow_id, version_id)
    if version.state != "draft":
        raise HTTPException(status_code=409, detail="Published workflow versions are immutable")
    expected_revision = _derived_expected_revision(
        version, payload.expected_revision if payload else None
    )
    try:
        compiled = compile_workflow_graph(
            version.authoring_graph,
            capabilities=_workflow_graph_capabilities(),
            workflow_version_id=version.version_id,
            workflow_version_number=version.version_number,
        )
    except WorkflowGraphValidationError as exc:
        raise HTTPException(
            status_code=422,
            detail=_with_draft_revision(exc.validation, version),
        )

    saved = _update_compiled_draft(
        version,
        expected_revision=expected_revision,
        compiled_definition=compiled["compiled_definition"],
        compiled_plan=compiled["compiled_plan"],
        validation=compiled["validation_result"],
    )
    return _with_draft_revision(compiled, saved)


@router.post("/workflows/{workflow_id}/versions/{version_id}/publish")
async def publish_workflow_version(
    workflow_id: str,
    version_id: str,
    payload: WorkflowPublishRequest,
) -> dict[str, Any]:
    _require_v2()
    _require_mutable_workflow(workflow_id)
    version = _version_for_workflow(workflow_id, version_id)
    expected_revision = _derived_expected_revision(
        version, payload.expected_revision
    )
    try:
        compiled = compile_workflow_graph(
            version.authoring_graph,
            capabilities=_workflow_graph_capabilities(),
            workflow_version_id=version.version_id,
            workflow_version_number=version.version_number,
        )
        version = workflow_version_store().publish_version(
            version_id,
            expected_revision=expected_revision,
            authoring_graph=version.authoring_graph,
            compiled_definition=compiled["compiled_definition"],
            compiled_plan=compiled["compiled_plan"],
            validation=compiled["validation_result"],
        )
    except WorkflowGraphValidationError as exc:
        raise HTTPException(
            status_code=422,
            detail=_with_draft_revision(exc.validation, version),
        )
    except StaleWorkflowDraftError as exc:
        raise _canvas_error("stale_draft", str(exc), status_code=409) from exc
    except PublishedWorkflowVersionError as exc:
        raise HTTPException(status_code=409, detail=str(exc))
    except (WorkflowVersionError, ValueError) as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    return asdict(version)


@router.post(
    "/workflows/{workflow_id}/versions/{version_id}/test-run",
    status_code=201,
)
async def prepare_workflow_trial_run(
    workflow_id: str,
    version_id: str,
    payload: WorkflowTrialRunRequest,
) -> dict[str, Any]:
    """Compile a draft server-side and prepare a real, isolated run snapshot."""
    _require_v2()
    _require_mutable_workflow(workflow_id)
    version = _version_for_workflow(workflow_id, version_id)
    if version.state != "draft":
        raise HTTPException(status_code=409, detail="只能试运行工作流草稿")
    expected_revision = _derived_expected_revision(version, payload.expected_revision)
    workspace = _resolve_workspace(payload.workspace_id)
    repo_path = Path(str(workspace["repo_path"])).expanduser().resolve()
    if not repo_path.exists() or not repo_path.is_dir():
        raise HTTPException(
            status_code=422,
            detail=f"工作空间源码目录不可用：{repo_path}",
        )
    try:
        compiled = compile_workflow_graph(
            version.authoring_graph,
            capabilities=_workflow_graph_capabilities(),
            workflow_version_id=version.version_id,
            workflow_version_number=version.version_number,
        )
    except WorkflowGraphValidationError as exc:
        raise HTTPException(
            status_code=422,
            detail=_with_draft_revision(exc.validation, version),
        )

    if payload.node_id:
        try:
            compiled = _diagnostic_node_trial(compiled, payload.node_id)
        except ValueError as exc:
            raise HTTPException(status_code=422, detail=str(exc)) from exc

    resolved_inputs = dict(payload.inputs)
    for input_definition in compiled["compiled_definition"].get("inputs") or []:
        if str(input_definition.get("resolver") or "") == "workspace":
            resolved_inputs[str(input_definition["id"])] = str(repo_path)
    try:
        WorkbenchTaskRunPreparer.preflight_inputs(
            workflow_snapshot=compiled["compiled_definition"],
            inputs=resolved_inputs,
        )
    except (FileNotFoundError, ValueError) as exc:
        raise HTTPException(
            status_code=422,
            detail=f"工作流输入不完整或无效：{exc}",
        ) from exc

    saved = None
    if expected_revision is not None:
        saved = _update_compiled_draft(
            version,
            expected_revision=expected_revision,
            compiled_definition=compiled["compiled_definition"],
            compiled_plan=compiled["compiled_plan"],
            validation=compiled["validation_result"],
        )

    root = settings.data_path / "workbench"
    trial_workflow_store = WorkflowStore(root / "trial_workflows.db")
    trial_workflow_store.save_workflow(compiled["compiled_definition"])
    try:
        prepared = WorkbenchTaskRunPreparer(
            artifact_root=root / "task_runs",
            workflow_store=trial_workflow_store,
            evidence_memory=EvidenceMemoryStore(root / "evidence_memory.db"),
            semantic_library=TestSemanticLibraryStore(root / "test_semantics.db"),
        ).prepare(
            workflow_id=workflow_id,
            workspace_id=payload.workspace_id,
            repo_path=str(repo_path),
            inputs=resolved_inputs,
        )
    except (FileNotFoundError, ValueError) as exc:
        if saved is not None:
            raise HTTPException(
                status_code=500,
                detail=f"试运行提交后准备失败，请查看服务端诊断：{exc}",
            ) from exc
        raise HTTPException(
            status_code=422,
            detail=f"工作流输入不完整或无效：{exc}",
        ) from exc
    prepared.task_bundle["compiled_definition"] = compiled["compiled_definition"]
    prepared.task_bundle["compiled_plan"] = compiled["compiled_plan"]
    prepared.task_bundle["workflow_version_id"] = version.version_id
    prepared.task_bundle["trial_run"] = True
    prepared.task_bundle["diagnostic"] = {
        "kind": "node_trial" if payload.node_id else "workflow_trial",
        "node_id": payload.node_id or None,
        "not_a_formal_delivery": True,
    }
    task_run_file = Path(prepared.artifact_dir) / "task_run.json"
    task_run_file.write_text(
        json.dumps(asdict(prepared), ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    (Path(prepared.artifact_dir) / "task_bundle.json").write_text(
        json.dumps(prepared.task_bundle, ensure_ascii=False, indent=2, sort_keys=True),
        encoding="utf-8",
    )
    refresh_run_snapshot_v3(prepared.artifact_dir)
    if saved is None:
        saved = _update_compiled_draft(
            version,
            compiled_definition=compiled["compiled_definition"],
            compiled_plan=compiled["compiled_plan"],
            validation=compiled["validation_result"],
        )
    return {
        "status": "prepared",
        "task_run_id": prepared.task_run_id,
        "workflow_id": workflow_id,
        "workflow_version_id": version_id,
        "workspace_id": payload.workspace_id,
        "compiled_plan": compiled["compiled_plan"],
        "draft_revision": saved.draft_revision,
        "diagnostic": prepared.task_bundle["diagnostic"],
    }


def _diagnostic_node_trial(compiled: dict[str, Any], node_id: str) -> dict[str, Any]:
    """Keep the public compiler contract, but execute exactly one executable node.

    This is intentionally derived from the compiled graph rather than from a
    separate trial DSL, so readiness, Harness, network policy and collection
    use the same task-run path as a normal execution.
    """
    plan = dict(compiled["compiled_plan"])
    selected = next(
        (item for item in plan.get("nodes") or [] if str(item.get("graph_node_id")) == node_id),
        None,
    )
    if not isinstance(selected, dict):
        raise ValueError("请选择一个可执行节点后再试运行")
    step_id = str(selected.get("node_id") or "")
    if not step_id:
        raise ValueError("所选节点缺少可执行步骤")
    definition = dict(compiled["compiled_definition"])
    definition["steps"] = [
        item for item in definition.get("steps") or []
        if isinstance(item, dict) and str(item.get("id") or "") == step_id
    ]
    if not definition["steps"]:
        raise ValueError("所选节点不是可试运行的执行节点")
    declared_input_ids = {
        str(item.get("id") or "")
        for item in definition.get("inputs") or []
        if isinstance(item, dict)
    }
    required_inputs: set[str] = set()
    for target_port, resolved in (selected.get("resolved_input_bindings") or {}).items():
        bindings = resolved if isinstance(resolved, list) else [resolved]
        found_source_input = False
        for binding in bindings:
            if not isinstance(binding, dict):
                continue
            source_input_id = str(binding.get("source_input_id") or "")
            if source_input_id:
                required_inputs.add(source_input_id)
                found_source_input = True
        if not found_source_input and str(target_port) in declared_input_ids:
            required_inputs.add(str(target_port))
    definition["inputs"] = [
        item for item in definition.get("inputs") or []
        if isinstance(item, dict) and str(item.get("id") or "") in required_inputs
    ]
    definition["outputs"] = [
        item for item in definition.get("outputs") or []
        if isinstance(item, dict) and str(item.get("from") or item.get("source") or "") == step_id
    ]
    plan["nodes"] = [{**selected, "depends_on": []}]
    plan["topological_order"] = [step_id]
    return {**compiled, "compiled_definition": definition, "compiled_plan": plan}


def _version_for_workflow(workflow_id: str, version_id: str):
    try:
        version = workflow_version_store().get_version(version_id)
    except KeyError:
        raise HTTPException(status_code=404, detail=f"Unknown workflow version: {version_id}")
    if version.workflow_id != workflow_id:
        raise HTTPException(status_code=404, detail=f"Unknown workflow version: {version_id}")
    return version


def _require_v3_mutable_draft(workflow_id: str, version_id: str):
    version = _version_for_workflow(workflow_id, version_id)
    if version.state != "draft":
        raise HTTPException(status_code=409, detail="Published workflow versions are immutable")
    if version.authoring_graph.get("schema_version") != 3:
        raise HTTPException(status_code=409, detail="Canvas commands require a V3 workflow draft")
    return version


def _assert_edge_ports_exist(
    graph: dict[str, Any],
    source: dict[str, Any],
    target: dict[str, Any],
    *,
    exclude_edge_id: str = "",
) -> None:
    nodes = {
        str(node.get("id") or ""): node
        for node in graph.get("nodes") or []
        if isinstance(node, dict)
    }
    source_id = str(source.get("node_id") or "")
    target_id = str(target.get("node_id") or "")
    source_port = str(source.get("port_id") or "")
    target_port = str(target.get("port_id") or "")
    source_node, target_node = nodes.get(source_id), nodes.get(target_id)
    if not source_node or not target_node:
        raise _canvas_error("edge_node_unknown", "Source and target nodes must exist")
    source_ports = {
        str(port.get("id") or ""): str(port.get("type") or "")
        for port in (source_node.get("ports") or {}).get("outputs") or []
        if isinstance(port, dict)
    }
    target_ports = {
        str(port.get("id") or ""): port
        for port in (target_node.get("ports") or {}).get("inputs") or []
        if isinstance(port, dict)
    }
    if source_port not in source_ports or target_port not in target_ports:
        raise _canvas_error("edge_port_unknown", "Source and target ports must exist")
    target_definition = target_ports[target_port]
    occupied = any(
        str(edge.get("kind") or "") == "data"
        and str(edge.get("id") or "") != exclude_edge_id
        and str((edge.get("target") or {}).get("node_id") or "") == target_id
        and str((edge.get("target") or {}).get("port_id") or "") == target_port
        for edge in graph.get("edges") or []
        if isinstance(edge, dict)
    )
    if occupied and not bool(target_definition.get("collection")):
        raise _canvas_error("multiple_edges_to_single_input", "该输入已绑定")
    target_type = str(target_definition.get("type") or "")
    if not _port_types_compatible(source_ports[source_port], target_type):
        raise _canvas_error(
            "port_type_mismatch",
            f"端口类型不兼容：{source_ports[source_port]} → {target_type}",
        )


def _port_types_compatible(source_type: str, target_type: str) -> bool:
    return source_type == target_type or source_type == "any" or target_type == "any"


def _find_canvas_port(
    graph: dict[str, Any], node_id: str, port_id: str
) -> dict[str, Any]:
    node = next(
        (item for item in graph.get("nodes") or [] if isinstance(item, dict) and str(item.get("id") or "") == node_id),
        None,
    )
    if node is None:
        raise HTTPException(status_code=404, detail=f"Unknown workflow node: {node_id}")
    ports = node.get("ports") if isinstance(node.get("ports"), dict) else {}
    for direction in ("inputs", "outputs"):
        for port in ports.get(direction) or []:
            if isinstance(port, dict) and str(port.get("id") or "") == port_id:
                return port
    raise HTTPException(status_code=404, detail=f"Unknown workflow port: {port_id}")


def _backend_commit_sha() -> str:
    return backend_commit_sha()


def _workflow_graph_capabilities() -> dict[str, Any]:
    capabilities = workflow_handler_capability_snapshot()
    providers: dict[str, dict[str, Any]] = {
        "builtin-llm": {"available": True, "mcp_profiles": []},
    }
    for provider_id, spec in external_agent_provider_specs().items():
        providers[provider_id] = {
            "available": bool(spec.command),
            "mcp_profiles": sorted(str(item) for item in spec.mcp_profiles),
        }
    for runtime in list_agent_runtimes_sync(enabled=True):
        runtime_id = str(runtime.get("id") or "").strip()
        if not runtime_id:
            continue
        mcp_profile = str(runtime.get("mcp_profile") or "").strip()
        providers[f"agent-runtime:{runtime_id}"] = {
            "available": bool(str(runtime.get("command") or "").strip()),
            "mcp_profiles": [mcp_profile] if mcp_profile else [],
        }
    return {
        **capabilities,
        "providers": providers,
        "skills": [
            "artifact-contract",
            "black-box-test-design",
            "coverage-gap-analysis",
            "defect-triage-regression",
            "performance-reliability-testing",
            "sfmea",
            "source-evidence-first",
            "storage-flow-analysis",
            "test-execution-orchestration",
            "test-strategy-planning",
        ],
    }


def _resolve_workspace(workspace_id: str) -> dict[str, Any]:
    try:
        with sqlite3.connect(str(settings.sqlite_db)) as db:
            db.row_factory = sqlite3.Row
            row = db.execute(
                "SELECT id, name, repo_path FROM workspaces WHERE id = ?",
                (workspace_id,),
            ).fetchone()
    except sqlite3.Error as exc:
        raise HTTPException(status_code=503, detail=f"工作空间存储不可用：{exc}")
    if row is None:
        raise HTTPException(status_code=404, detail=f"工作空间不存在：{workspace_id}")
    return dict(row)
